export const IDENTITY_MERGE_POLICIES = [
  'subject_repoint',
  'dedupe_then_repoint',
  'operational_actor_repoint',
  'historical_preserve',
  'security_revoke',
  'hard_conflict',
] as const;

export type IdentityMergeReferencePolicy = typeof IDENTITY_MERGE_POLICIES[number];

export type IdentityMergeReference = Readonly<{
  table: string;
  column: string;
  policy: IdentityMergeReferencePolicy;
  notes: string;
  backend?: 'postgres';
}>;

export function mergeReferenceKey(table: string, column: string): string {
  return `${table}.${column}`;
}

const ref = (
  table: string,
  column: string,
  policy: IdentityMergeReferencePolicy,
  notes: string,
  backend?: 'postgres',
): IdentityMergeReference => ({ table, column, policy, notes, ...(backend ? { backend } : {}) });

export const IDENTITY_MERGE_REFERENCE_REGISTRY: readonly IdentityMergeReference[] = [
  ref('fellowships', 'coordinator_id', 'hard_conflict', 'Community coordination requires explicit reassignment before an identity merge.'),
  ref('fellowship_members', 'person_id', 'hard_conflict', 'Fellowship membership collisions require explicit review before an identity merge.'),
  ref('workflow_templates', 'default_assignee_id', 'hard_conflict', 'Automatic follow-up ownership requires explicit reassignment before an identity merge.'),
  ref('workflow_runs', 'person_id', 'hard_conflict', 'Follow-up subjects require explicit review before an identity merge.'),
  ref('workflow_tasks', 'assignee_id', 'hard_conflict', 'Task ownership requires explicit reassignment before an identity merge.'),
  ref('workflow_tasks', 'updated_by', 'historical_preserve', 'Task update attribution stays with the original operator.'),
  ref('activity_score_config', 'updated_by_person_id', 'operational_actor_repoint', 'Current configuration attribution follows the canonical operator.'),
  ref('audit_events', 'actor_person_id', 'historical_preserve', 'Immutable export audit attribution remains on the original identity.'),
  ref('blockout_dates', 'person_id', 'dedupe_then_repoint', 'Overlapping person blockouts must be deduplicated before reassignment.'),
  ref('campus_memberships', 'person_id', 'dedupe_then_repoint', 'Campus membership and privilege rows require explicit collision handling.'),
  ref('contact_owner_mutation_claims', 'expected_person_id', 'historical_preserve', 'Append-only ownership mutation precondition remains historically exact.'),
  ref('contact_owner_mutation_claims', 'resulting_person_id', 'historical_preserve', 'Append-only ownership mutation result remains historically exact.'),
  ref('contact_ownership_events', 'actor_person_id', 'historical_preserve', 'Ownership audit actor remains the identity that performed the event.'),
  ref('contact_ownership_events', 'person_id', 'historical_preserve', 'Ownership audit subject remains the identity recorded at event time.'),
  ref('contact_ownership_events', 'previous_person_id', 'historical_preserve', 'Previous ownership history must not be rewritten after a merge.'),
  ref('gift_results', 'person_id', 'subject_repoint', 'Giving result attribution follows the canonical member without exposing amounts.'),
  ref('group_attendance', 'recorded_by', 'historical_preserve', 'Attendance recorder attribution remains historically exact.'),
  ref('group_attendance_tokens', 'person_id', 'security_revoke', 'Outstanding attendance credentials for the loser must be revoked.'),
  ref('group_join_requests', 'decided_by', 'historical_preserve', 'Join-request decision attribution remains historically exact.'),
  ref('group_join_requests', 'person_id', 'dedupe_then_repoint', 'Pending and decided requests may collide for the canonical member.'),
  ref('group_members', 'person_id', 'dedupe_then_repoint', 'Group membership uniqueness must be resolved before reassignment.'),
  ref('household_members', 'person_id', 'hard_conflict', 'Different household membership is a merge risk requiring an explicit decision.'),
  ref('identity_account_operations', 'result_person_id', 'historical_preserve', 'Account-operation result receipts remain append-only and exact.'),
  ref('identity_account_operations', 'target_person_id', 'historical_preserve', 'Account-operation target receipts remain append-only and exact.'),
  ref('identity_account_proof_uses', 'person_id', 'historical_preserve', 'Consumed proof attribution remains on the original identity.'),
  ref('identity_account_review_cases', 'reviewer_person_id', 'historical_preserve', 'Review attribution remains on the original reviewer identity.'),
  ref('identity_audit_events', 'actor_person_id', 'historical_preserve', 'Identity audit actor is immutable historical evidence.'),
  ref('identity_audit_events', 'subject_person_id', 'historical_preserve', 'Identity audit subject is immutable historical evidence.'),
  ref('identity_business_intent_receipts', 'person_id', 'historical_preserve', 'Completed business-intent receipts remain immutable identity evidence.'),
  ref('identity_business_intents', 'result_person_id', 'historical_preserve', 'Business-intent results remain bound to their verified operation.'),
  ref('identity_challenge_proof_uses', 'person_id', 'historical_preserve', 'Consumed challenge proof remains attached to its original subject.'),
  ref('identity_challenges', 'person_id', 'security_revoke', 'Every unconsumed challenge for the loser must be revoked.'),
  ref('identity_claim_operations', 'expected_owner_person_id', 'historical_preserve', 'Claim preconditions are immutable operation evidence.'),
  ref('identity_claim_operations', 'result_person_id', 'historical_preserve', 'Claim results are immutable operation evidence.'),
  ref('identity_observations', 'linked_person_id', 'subject_repoint', 'Resolved observations follow the canonical member identity.'),
  ref('identity_newcomer_intents', 'provisional_person_id', 'hard_conflict', 'Reserved newcomer identities require explicit collision resolution.'),
  ref('identity_person_canonical_keys', 'person_id', 'hard_conflict', 'Canonical identity keys are unique and require collision resolution.'),
  ref('identity_recovery_cases', 'person_id', 'historical_preserve', 'Recovery case targets remain historically exact.'),
  ref('identity_recovery_cases', 'reviewer_person_id', 'historical_preserve', 'Recovery reviewer attribution remains historically exact.'),
  ref('identity_recovery_decisions', 'actor_person_id', 'historical_preserve', 'Recovery approval actors remain immutable evidence.'),
  ref('identity_recovery_decisions', 'expected_person_id', 'historical_preserve', 'Recovery decision preconditions remain immutable evidence.'),
  ref('identity_recovery_decisions', 'expected_reachable_owner_person_id', 'historical_preserve', 'Recovery reachable-owner preconditions remain immutable evidence.'),
  ref('identity_recovery_holds', 'expected_person_id', 'historical_preserve', 'Recovery hold preconditions remain immutable evidence.'),
  ref('identity_recovery_holds', 'expected_reachable_owner_person_id', 'historical_preserve', 'Recovery hold owner preconditions remain immutable evidence.'),
  ref('identity_recovery_holds', 'first_approver_person_id', 'historical_preserve', 'First-approver attribution remains immutable evidence.'),
  ref('identity_recovery_owner_snapshots', 'expected_owner_person_id', 'historical_preserve', 'Reviewed ownership snapshots remain immutable evidence.'),
  ref('identity_resolution_cases', 'candidate_person_id', 'historical_preserve', 'Resolution candidates remain fixed review evidence.'),
  ref('identity_resolution_cases', 'person_a_id', 'historical_preserve', 'Resolution pair evidence remains fixed after merge.'),
  ref('identity_resolution_cases', 'person_b_id', 'historical_preserve', 'Resolution pair evidence remains fixed after merge.'),
  ref('identity_resolution_cases', 'reviewer_person_id', 'historical_preserve', 'Resolution reviewer attribution remains historically exact.'),
  ref('identity_session_delivery_claims', 'person_id', 'historical_preserve', 'Session-delivery receipts remain immutable replay evidence.'),
  ref('identity_session_epoch_claims', 'person_id', 'historical_preserve', 'Session epoch mutation claims remain immutable evidence.'),
  ref('identity_source_attachment_commits', 'person_id', 'historical_preserve', 'Source attachment commit receipts remain immutable evidence.'),
  ref('identity_source_attachment_receipts', 'person_id', 'historical_preserve', 'Source attachment receipts remain immutable evidence.'),
  ref('identity_source_provisional_receipts', 'person_id', 'hard_conflict', 'One provisional receipt per person requires collision resolution.'),
  ref('identity_source_records', 'linked_person_id', 'subject_repoint', 'Live source linkage follows the canonical member identity.'),
  ref('identity_source_records', 'provisional_person_id', 'hard_conflict', 'Unique provisional source ownership requires collision resolution.'),
  ref('learning_activity_events', 'person_id', 'subject_repoint', 'Learning activity follows the canonical learner identity.'),
  ref('learning_canvas_oauth_states', 'actor_person_id', 'security_revoke', 'Outstanding Canvas OAuth state for the loser must be revoked.'),
  ref('learning_google_oauth_states', 'actor_person_id', 'security_revoke', 'Outstanding Google OAuth state for the loser must be revoked.'),
  ref('learning_identity_links', 'person_id', 'hard_conflict', 'Provider identity uniqueness requires explicit collision resolution.'),
  ref('learning_programs', 'created_by_person_id', 'operational_actor_repoint', 'Current learning program ownership follows the canonical operator.'),
  ref('learning_programs', 'updated_by_person_id', 'operational_actor_repoint', 'Current learning program attribution follows the canonical operator.'),
  ref('learning_provider_connections', 'created_by_person_id', 'operational_actor_repoint', 'Current provider connection ownership follows the canonical operator.'),
  ref('learning_provider_connections', 'updated_by_person_id', 'operational_actor_repoint', 'Current provider connection attribution follows the canonical operator.'),
  ref('ministries', 'leader_person_id', 'subject_repoint', 'Active ministry leadership follows the canonical member.'),
  ref('newcomer_activity', 'actor_person_id', 'historical_preserve', 'Newcomer activity actor remains historically exact.'),
  ref('newcomer_notes', 'author_person_id', 'historical_preserve', 'Newcomer note author remains historically exact.'),
  ref('newcomer_submissions', 'assignee_person_id', 'operational_actor_repoint', 'Open newcomer assignment follows the canonical operator.'),
  ref('newcomer_submissions', 'linked_person_id', 'subject_repoint', 'Newcomer linkage follows the canonical member identity.'),
  ref('onboarding_acknowledgements', 'actor_person_id', 'historical_preserve', 'Onboarding acknowledgement attribution remains historically exact.'),
  ref('people', 'merged_into_person_id', 'hard_conflict', 'People self-reference is governed only by one-hop canonical redirects.'),
  ref('people_import_mappings', 'created_by_person_id', 'historical_preserve', 'Import mapping creator attribution remains historically exact.'),
  ref('person_contact_links', 'person_id', 'dedupe_then_repoint', 'Shared and primary contact links require collision-aware reassignment.'),
  ref('person_external_identities', 'person_id', 'hard_conflict', 'External identity uniqueness requires an explicit conflict decision.'),
  ref('person_interests', 'person_id', 'dedupe_then_repoint', 'Person-interest uniqueness must be deduplicated before reassignment.'),
  ref('person_merge_approvals', 'approver_person_id', 'historical_preserve', 'Merge approval attribution is append-only security evidence.'),
  ref('person_merge_conflict_decisions', 'decided_by_person_id', 'historical_preserve', 'Merge conflict decision attribution is append-only evidence.'),
  ref('person_merge_events', 'approved_by_person_id', 'historical_preserve', 'Legacy merge approval attribution remains immutable evidence.'),
  ref('person_merge_events', 'canonical_person_id', 'historical_preserve', 'Legacy merge event canonical identity remains immutable evidence.'),
  ref('person_merge_events', 'loser_person_id', 'historical_preserve', 'Legacy merge event loser identity remains immutable evidence.'),
  ref('person_merge_events', 'requested_by_person_id', 'historical_preserve', 'Legacy merge request attribution remains immutable evidence.'),
  ref('person_merge_mutation_receipts', 'canonical_person_id', 'historical_preserve', 'Execution-produced mutation evidence keeps its exact canonical binding.'),
  ref('person_merge_mutation_receipts', 'loser_person_id', 'historical_preserve', 'Execution-produced mutation evidence keeps its exact loser binding.'),
  ref('person_merge_operations', 'canonical_person_id', 'historical_preserve', 'Operation canonical binding remains immutable preview evidence.'),
  ref('person_merge_operations', 'loser_person_id', 'historical_preserve', 'Operation loser binding remains immutable preview evidence.'),
  ref('person_merge_operations', 'requested_by_person_id', 'historical_preserve', 'Merge request attribution remains immutable evidence.'),
  ref('person_merge_redirects', 'canonical_person_id', 'historical_preserve', 'Canonical redirects are terminal historical routing records.'),
  ref('person_merge_redirects', 'loser_person_id', 'historical_preserve', 'Loser redirects are terminal historical routing records.'),
  ref('person_merge_rollback_approvals', 'approver_person_id', 'historical_preserve', 'Rollback approval attribution is append-only security evidence.'),
  ref('person_merge_rollback_operations', 'requested_by_person_id', 'historical_preserve', 'Rollback request attribution remains immutable evidence.'),
  ref('person_notes', 'person_id', 'subject_repoint', 'Member notes follow the canonical subject while bodies remain untouched.'),
  ref('planning_center_person_mappings', 'person_id', 'hard_conflict', 'Provider person mappings require reviewed collision handling and never silently transfer.'),
  ref('roster_assignments', 'person_id', 'dedupe_then_repoint', 'Roster assignment collisions require explicit deduplication.'),
  ref('service_attendance', 'recorded_by_person_id', 'historical_preserve', 'Service attendance recorder remains historically exact.'),
  ref('service_attendance', 'updated_by_person_id', 'historical_preserve', 'Service attendance editor remains historically exact.'),
  ref('service_type_checkin_events', 'closed_by_person_id', 'historical_preserve', 'Check-in close attribution remains historically exact.'),
  ref('service_type_checkin_events', 'created_by_person_id', 'historical_preserve', 'Check-in creation attribution remains historically exact.'),
  ref('team_applications', 'person_id', 'dedupe_then_repoint', 'Pending application uniqueness requires collision resolution.'),
  ref('team_members', 'person_id', 'dedupe_then_repoint', 'Team membership uniqueness must be deduplicated before reassignment.'),
  ref('testimonies', 'person_id', 'subject_repoint', 'Published testimony attribution follows the canonical member.'),
  ref('tokens', 'person_id', 'security_revoke', 'Every unused loser authentication token must be revoked.'),
  ref('verified_contact_owners', 'person_id', 'hard_conflict', 'Verified authentication ownership never silently transfers or unions.'),

  ref('event_admins', 'person_id', 'dedupe_then_repoint', 'Event administrator uniqueness requires collision-aware reassignment.', 'postgres'),
  ref('gifts', 'person_id', 'subject_repoint', 'Gift donor attribution follows the canonical member without inspecting amounts.', 'postgres'),
  ref('gifts', 'recorded_by', 'historical_preserve', 'Manual gift recorder attribution remains historically exact.', 'postgres'),
  ref('group_files', 'uploaded_by', 'historical_preserve', 'Group file uploader attribution remains historically exact.', 'postgres'),
  ref('prayer_items', 'approved_by', 'historical_preserve', 'Prayer approval attribution remains historically exact.', 'postgres'),
  ref('prayer_items', 'author_person_id', 'historical_preserve', 'Prayer author attribution remains historically exact.', 'postgres'),
  ref('recurring_gifts', 'person_id', 'hard_conflict', 'Recurring giving ownership conflicts require explicit resolution.', 'postgres'),
  ref('registrations', 'person_id', 'subject_repoint', 'Registration attribution follows the canonical member.', 'postgres'),
  ref('church_private.stripe_checkout_requests', 'last_action_by', 'historical_preserve', 'Private Stripe action attribution remains historically exact.', 'postgres'),
  ref('church_private.stripe_webhook_events', 'last_action_by', 'historical_preserve', 'Private Stripe webhook attribution remains historically exact.', 'postgres'),
];

export const IDENTITY_MERGE_TEXT_ACTOR_REGISTRY: readonly IdentityMergeReference[] = [
  ref('bulletins', 'updated_by', 'historical_preserve', 'Legacy textual editor attribution is never rewritten.'),
  ref('media', 'uploaded_by', 'historical_preserve', 'Legacy textual uploader attribution is never rewritten.'),
  ref('prayer_activity', 'author', 'historical_preserve', 'Legacy textual prayer author attribution is never rewritten.'),
  ref('prayer_sheets', 'updated_by', 'historical_preserve', 'Legacy textual editor attribution is never rewritten.'),
  ref('revisions', 'edited_by', 'historical_preserve', 'Legacy textual revision attribution is never rewritten.'),
  ref('sermons', 'updated_by', 'historical_preserve', 'Legacy textual editor attribution is never rewritten.'),
  ref('team_applications', 'decided_by', 'historical_preserve', 'Legacy textual decision attribution is never rewritten.'),
  ref('external_ids', 'entity_id', 'hard_conflict', 'Polymorphic external identity references require explicit review.'),
  ref('identity_account_operations', 'reserved_person_id', 'hard_conflict', 'Reserved person identifiers are semantic identity references despite lacking a foreign key.'),
  ref('identity_source_provisional_operations', 'reserved_person_id', 'hard_conflict', 'Provisional reservations are semantic person references despite lacking a foreign key.'),
  ref('person_notes', 'author_email', 'historical_preserve', 'Legacy note author snapshots remain immutable historical attribution.'),
  ref('roster_assignments', 'assigned_by', 'historical_preserve', 'Legacy textual roster assigner attribution is never rewritten.'),
  ref('testimonies', 'author_name', 'historical_preserve', 'Testimony author snapshots remain immutable historical attribution.'),
];
