import data from './s2t-table.json';

// Generated by scripts/generate-s2t.mjs from OpenCC dictionaries (chars + phrases).
const map = data.map as Record<string, string>;
const maxLen = data.maxLen as number;

/** Convert Simplified Chinese text to Traditional using greedy longest-match. */
export function toTraditional(text: string): string {
  let out = '';
  let i = 0;
  while (i < text.length) {
    let matched = false;
    for (let len = Math.min(maxLen, text.length - i); len > 1; len--) {
      const rep = map[text.slice(i, i + len)];
      if (rep !== undefined) {
        out += rep;
        i += len;
        matched = true;
        break;
      }
    }
    if (!matched) {
      const ch = text[i];
      out += map[ch] ?? ch;
      i++;
    }
  }
  return out;
}
