-- church4christ Postgres schema (Supabase backend).
-- Part 1: SQLite-compat functions. The app's SQL (and this schema's DEFAULTs)
-- call datetime('now', ...)/date('now', ...) exactly as they do on D1; these
-- functions implement the SQLite modifier forms the repo actually uses:
--   ±N minutes/hours/days/months/years, 'weekday N', 'start of day'.
-- All math is UTC, matching SQLite's datetime('now').
-- GOTCHA: Postgres parses bare date('literal') as a CAST ('now'::date) at parse
-- time, so a single-arg date('now') never reaches these functions; app SQL uses
-- date('now', 'start of day') instead (a tripwire test bans the bare form).

CREATE OR REPLACE FUNCTION sqlite_compat_apply(base timestamp, mods text[])
RETURNS timestamp
LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE
  m text;
  mm text[];
BEGIN
  FOREACH m IN ARRAY mods LOOP
    m := lower(btrim(m));
    mm := regexp_match(m, '^([+-]?\d+(?:\.\d+)?)\s+(second|minute|hour|day|month|year)s?$');
    IF mm IS NOT NULL THEN
      base := base + (mm[1] || ' ' || mm[2])::interval;
      CONTINUE;
    END IF;
    mm := regexp_match(m, '^weekday\s+(\d)$');
    IF mm IS NOT NULL THEN
      base := base + make_interval(days => ((mm[1]::int - EXTRACT(dow FROM base)::int) % 7 + 7) % 7);
      CONTINUE;
    END IF;
    IF m = 'start of day' THEN base := date_trunc('day', base); CONTINUE; END IF;
    IF m = 'start of month' THEN base := date_trunc('month', base); CONTINUE; END IF;
    IF m = 'start of year' THEN base := date_trunc('year', base); CONTINUE; END IF;
    RAISE EXCEPTION 'unsupported sqlite datetime modifier: %', m;
  END LOOP;
  RETURN base;
END;
$$;

CREATE OR REPLACE FUNCTION sqlite_compat_base(ts text)
RETURNS timestamp
LANGUAGE sql STABLE AS $$
  SELECT CASE
    WHEN lower(btrim(ts)) = 'now' THEN (now() AT TIME ZONE 'utc')
    ELSE ts::timestamp
  END;
$$;

CREATE OR REPLACE FUNCTION datetime(ts text, VARIADIC mods text[] DEFAULT '{}')
RETURNS text
LANGUAGE sql STABLE AS $$
  SELECT to_char(sqlite_compat_apply(sqlite_compat_base(ts), mods), 'YYYY-MM-DD HH24:MI:SS');
$$;

CREATE OR REPLACE FUNCTION date(ts text, VARIADIC mods text[] DEFAULT '{}')
RETURNS text
LANGUAGE sql STABLE AS $$
  SELECT to_char(sqlite_compat_apply(sqlite_compat_base(ts), mods), 'YYYY-MM-DD');
$$;

-- SQLite's max()/min() double as scalar greatest()/least() when given 2+ args;
-- Postgres's max()/min() are single-arg aggregates only, so the app's
-- SUM(MAX(0, needed - filled)) / SUM(MIN(needed, filled)) staffing math (ministryDb,
-- adminOverviewDb, teamDb) needs a 2-arg scalar overload. Add it under the same
-- names so that SQL runs unchanged on both backends — Postgres resolves by arity,
-- leaving the 1-arg aggregate untouched (max(x) / min(x) still aggregate). Every
-- call site passes non-null small counts, so greatest/least (which, unlike SQLite,
-- skip NULLs) match SQLite's scalar semantics here. Returns integer to mirror
-- SQLite/D1: SUM(integer) is bigint, read back as a JS number via int8AsNumber.
CREATE OR REPLACE FUNCTION max(a bigint, b bigint)
RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT greatest(a, b)::integer $$;

CREATE OR REPLACE FUNCTION min(a bigint, b bigint)
RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT least(a, b)::integer $$;


-- ---------------------------------------------------------------------------
-- Part 2: schema. A fresh consolidated snapshot of the D1 migrations
--   migrations/0001_init.sql, 0002_email.sql, 0003_people.sql
-- ported to Postgres. Porting rules (from the plan):
--   * `INTEGER PRIMARY KEY` -> `integer PRIMARY KEY GENERATED BY DEFAULT AS
--     IDENTITY` (BY DEFAULT: the seed inserts explicit ids).
--   * TEXT/INTEGER/REAL types and every CHECK/NOT NULL/UNIQUE/DEFAULT/REFERENCES
--     clause kept verbatim; `DEFAULT (datetime('now'))` resolves via the compat
--     functions above.
--   * ALTER TABLE ADD COLUMN from 0003 is folded into the base CREATE TABLE.
--   * Partial indexes are valid Postgres and kept verbatim.
-- Tables and indexes appear in the same order as the D1 source.

-- === from migrations/0001_init.sql ===

-- people: unified identities (members, volunteers, editors, admins)
CREATE TABLE people (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  display_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,            -- stored lowercase
  phone TEXT,
  avatar_url TEXT,
  role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('member','editor','admin')),
  active INTEGER NOT NULL DEFAULT 1,
  session_epoch INTEGER NOT NULL DEFAULT 0,
  calendar_token TEXT UNIQUE,
  lang TEXT CHECK (lang IN ('en','zh')),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT,
  -- folded from migrations/0003_people.sql (ALTER TABLE ADD COLUMN), appended in
  -- ALTER order to match D1's post-migration column layout.
  birthday TEXT,
  address TEXT,
  membership_status TEXT NOT NULL DEFAULT 'visitor'
    CHECK (membership_status IN ('visitor','regular','member','inactive')),
  joined_on TEXT
);

CREATE TABLE ministries (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  icon TEXT NOT NULL DEFAULT '',
  cover_key TEXT,
  leader_person_id INTEGER REFERENCES people(id),
  meeting_time TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  sort INTEGER NOT NULL DEFAULT 0,
  deleted_at TEXT
);
CREATE TABLE ministry_i18n (
  ministry_id INTEGER NOT NULL REFERENCES ministries(id),
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  name TEXT NOT NULL,
  intro TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (ministry_id, locale)
);

CREATE TABLE teams (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ministry_id INTEGER REFERENCES ministries(id),
  sort INTEGER NOT NULL DEFAULT 0,
  deleted_at TEXT
);
CREATE TABLE team_i18n (
  team_id INTEGER NOT NULL REFERENCES teams(id),
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  name TEXT NOT NULL,
  PRIMARY KEY (team_id, locale)
);

CREATE TABLE positions (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  team_id INTEGER NOT NULL REFERENCES teams(id),
  sort INTEGER NOT NULL DEFAULT 0,
  deleted_at TEXT
);
CREATE TABLE position_i18n (
  position_id INTEGER NOT NULL REFERENCES positions(id),
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  name TEXT NOT NULL,
  PRIMARY KEY (position_id, locale)
);

CREATE TABLE team_members (
  team_id INTEGER NOT NULL REFERENCES teams(id),
  person_id INTEGER NOT NULL REFERENCES people(id),
  is_leader INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (team_id, person_id)
);

CREATE TABLE service_types (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  start_time TEXT,                        -- HH:MM 24h, optional
  end_time TEXT,
  sort INTEGER NOT NULL DEFAULT 0,
  deleted_at TEXT
);
CREATE TABLE service_type_i18n (
  service_type_id INTEGER NOT NULL REFERENCES service_types(id),
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  name TEXT NOT NULL,
  PRIMARY KEY (service_type_id, locale)
);

CREATE TABLE plans (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  service_type_id INTEGER NOT NULL REFERENCES service_types(id),
  plan_date TEXT NOT NULL,
  title TEXT,
  series TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT,
  UNIQUE (service_type_id, plan_date)
);

CREATE TABLE plan_positions (
  plan_id INTEGER NOT NULL REFERENCES plans(id),
  position_id INTEGER NOT NULL REFERENCES positions(id),
  needed INTEGER NOT NULL DEFAULT 1,
  open_signup INTEGER NOT NULL DEFAULT 0,
  UNIQUE (plan_id, position_id)
);

CREATE TABLE roster_assignments (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  plan_id INTEGER NOT NULL REFERENCES plans(id),
  position_id INTEGER NOT NULL REFERENCES positions(id),
  person_id INTEGER NOT NULL REFERENCES people(id),
  status TEXT NOT NULL DEFAULT 'U' CHECK (status IN ('U','C','D')),
  decline_reason TEXT,
  is_signup INTEGER NOT NULL DEFAULT 0,
  assigned_by TEXT,
  notified_at TEXT,
  responded_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT,
  UNIQUE (plan_id, position_id, person_id)
);

CREATE TABLE blockout_dates (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  person_id INTEGER NOT NULL REFERENCES people(id),
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  start_time TEXT,
  end_time TEXT,
  reason TEXT,
  recurrence_group TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE team_applications (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  person_id INTEGER NOT NULL REFERENCES people(id),
  team_id INTEGER NOT NULL REFERENCES teams(id),
  position_id INTEGER REFERENCES positions(id),
  message TEXT,
  status TEXT NOT NULL DEFAULT 'P' CHECK (status IN ('P','A','R')),
  decided_by TEXT,
  decided_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE UNIQUE INDEX idx_app_pending_unique
  ON team_applications (person_id, team_id) WHERE status = 'P';

CREATE TABLE person_interests (
  person_id INTEGER NOT NULL REFERENCES people(id),
  category TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (person_id, category)
);

CREATE TABLE gift_results (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  person_id INTEGER NOT NULL REFERENCES people(id),
  top_gifts_json TEXT NOT NULL,
  recommended_json TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE testimonies (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  person_id INTEGER REFERENCES people(id),
  author_name TEXT NOT NULL,
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  category TEXT,
  status TEXT NOT NULL DEFAULT 'P' CHECK (status IN ('P','A','R')),
  published_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
);

CREATE TABLE tokens (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  token_hash TEXT NOT NULL UNIQUE,
  person_id INTEGER NOT NULL REFERENCES people(id),
  purpose TEXT NOT NULL CHECK (purpose IN ('login','respond')),
  assignment_id INTEGER REFERENCES roster_assignments(id),
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Content
CREATE TABLE bulletins (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  service_type_id INTEGER NOT NULL REFERENCES service_types(id),
  bulletin_date TEXT NOT NULL,
  service_time_label TEXT,
  program_json TEXT,                       -- [{item,content,person}]
  offering_json TEXT,                      -- [{label,amount}]
  attendance_json TEXT,                    -- [{label,count}]
  memory_verse TEXT,
  flowers TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  publish_at TEXT,
  updated_by TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT,
  UNIQUE (service_type_id, bulletin_date)
);

CREATE TABLE bulletin_announcements (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  bulletin_id INTEGER NOT NULL REFERENCES bulletins(id),
  seq INTEGER NOT NULL DEFAULT 0,
  title TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL,
  link_url TEXT,
  link_label TEXT
);

CREATE TABLE sermons (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  service_type_id INTEGER NOT NULL REFERENCES service_types(id),
  sermon_date TEXT NOT NULL,
  title TEXT NOT NULL,
  speaker TEXT NOT NULL DEFAULT '',
  scripture TEXT,
  youtube_id TEXT,
  series TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  updated_by TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT,
  UNIQUE (service_type_id, sermon_date)
);

CREATE TABLE prayer_sheets (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sheet_date TEXT NOT NULL UNIQUE,
  locale TEXT CHECK (locale IN ('en','zh')),
  sections_json TEXT,                      -- [{heading,items[]}]
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  publish_at TEXT,
  updated_by TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
);

CREATE TABLE announcements (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  url TEXT,
  sort INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  starts_at TEXT,
  ends_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE announcement_i18n (
  announcement_id INTEGER NOT NULL REFERENCES announcements(id),
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  title TEXT NOT NULL,
  PRIMARY KEY (announcement_id, locale)
);

CREATE TABLE events (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  image_key TEXT,
  url TEXT,
  sort INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  starts_at TEXT,
  ends_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE event_i18n (
  event_id INTEGER NOT NULL REFERENCES events(id),
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  title TEXT NOT NULL,
  blurb TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (event_id, locale)
);

CREATE TABLE prayer_requests (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'new'
    CHECK (status IN ('new','praying','long_term','waiting','answered','cancelled')),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE prayer_activity (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  request_id INTEGER NOT NULL REFERENCES prayer_requests(id),
  author TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('prayed','comment','moved')),
  body TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE revisions (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  entity TEXT NOT NULL CHECK (entity IN
    ('bulletin','sermon','prayer_sheet','announcement','event')),
  entity_id INTEGER NOT NULL,
  snapshot_json TEXT NOT NULL,
  edited_by TEXT NOT NULL,
  edited_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE media (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  r2_key TEXT NOT NULL UNIQUE,
  filename TEXT NOT NULL,
  content_type TEXT NOT NULL,
  size INTEGER NOT NULL,
  uploaded_by TEXT,
  uploaded_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE external_ids (
  entity TEXT NOT NULL,
  entity_id INTEGER NOT NULL,
  system TEXT NOT NULL,
  external_id TEXT NOT NULL,
  UNIQUE (entity, entity_id, system)
);

CREATE INDEX idx_people_email ON people(email);
CREATE INDEX idx_teams_ministry ON teams(ministry_id);
CREATE INDEX idx_positions_team ON positions(team_id);
CREATE INDEX idx_team_members_person ON team_members(person_id);
CREATE INDEX idx_plans_date ON plans(plan_date);
CREATE INDEX idx_plan_positions_plan ON plan_positions(plan_id);
CREATE INDEX idx_roster_plan ON roster_assignments(plan_id);
CREATE INDEX idx_roster_person ON roster_assignments(person_id);
CREATE INDEX idx_blockouts_person ON blockout_dates(person_id);
CREATE INDEX idx_applications_team ON team_applications(team_id, status);
CREATE INDEX idx_gift_results_person ON gift_results(person_id, created_at);
CREATE INDEX idx_testimonies_status ON testimonies(status, locale);
CREATE INDEX idx_tokens_person ON tokens(person_id, purpose);
CREATE INDEX idx_bulletins_date ON bulletins(bulletin_date);
CREATE INDEX idx_bulletin_ann_bulletin ON bulletin_announcements(bulletin_id, seq);
CREATE INDEX idx_sermons_date ON sermons(sermon_date);
CREATE INDEX idx_prayer_requests_status ON prayer_requests(status, created_at);
CREATE INDEX idx_prayer_activity_request ON prayer_activity(request_id, created_at);
CREATE INDEX idx_revisions_entity ON revisions(entity, entity_id, edited_at);

-- === from migrations/0002_email.sql ===

CREATE TABLE email_rules (
  rule_key TEXT PRIMARY KEY CHECK (rule_key IN ('remind7','remind3','digestAM')),
  enabled INTEGER NOT NULL DEFAULT 0
);
INSERT INTO email_rules (rule_key, enabled) VALUES
  ('remind7', 1), ('remind3', 0), ('digestAM', 1);

CREATE TABLE email_templates (
  template_key TEXT NOT NULL CHECK (template_key IN ('remind','request','appResult','digestAM')),
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  subject TEXT NOT NULL,
  body TEXT NOT NULL,
  PRIMARY KEY (template_key, locale)
);

INSERT INTO email_templates (template_key, locale, subject, body) VALUES
  ('remind', 'en', 'Reminder: you''re serving on {date}',
    'Hi {name}, just a friendly reminder that you''re scheduled to serve as {position} on {date}. Please confirm here: {link}'),
  ('remind', 'zh', '服事提醒：{date}',
    '{name} 平安！温馨提醒您已安排于 {date} 担任 {position} 服事，请点击确认：{link}'),
  ('request', 'en', 'New serving request for {date}',
    'Hi {name}, we''d love to have you serve as {position} on {date}. Please let us know if you''re available: {link}'),
  ('request', 'zh', '服事邀请：{date}',
    '{name} 平安！诚邀您于 {date} 担任 {position} 服事，请点击回复是否方便：{link}'),
  ('appResult', 'en', 'Your team application update',
    'Hi {name}, thank you for applying to serve! We''re happy to let you know your application has been approved. View the details here: {link}'),
  ('appResult', 'zh', '您的服事申请结果',
    '{name} 平安！感谢您愿意委身服事，您的申请已获批准，欢迎点击查看详情：{link}'),
  ('digestAM', 'en', 'Your weekly serving digest',
    'Hi {name}, here''s a look at the upcoming serving schedule for your teams. Full details here: {link}'),
  ('digestAM', 'zh', '本周服事摘要',
    '{name} 平安！以下是您所在服事团队的近期安排，完整内容请点击：{link}');

CREATE TABLE email_log (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  to_email TEXT NOT NULL,
  to_name TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL,
  detail TEXT,
  status TEXT NOT NULL CHECK (status IN ('sent','delivered','opened','bounced','failed','devlog')),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_email_log_created ON email_log(created_at);

-- === from migrations/0003_people.sql (people ALTERs folded above) ===

-- households: one shared card per family unit. Soft-deleted (deleted_at) when the
-- last real member leaves; its name-only dependent rows are hard-deleted then.
CREATE TABLE households (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  address TEXT,
  phone TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
);

-- household_members: real members carry person_id; dependents (children or
-- account-less adults) are name-only rows with person_id NULL. role/is_primary
-- default to the common case (an adult, non-primary).
CREATE TABLE household_members (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  household_id INTEGER NOT NULL REFERENCES households(id),
  person_id INTEGER REFERENCES people(id),
  display_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'adult' CHECK (role IN ('adult','child')),
  is_primary INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- A real person belongs to at most one household (partial: dependents are exempt).
CREATE UNIQUE INDEX idx_household_members_person
  ON household_members(person_id) WHERE person_id IS NOT NULL;
-- Belt-and-braces uniqueness of a real person within a single household.
CREATE UNIQUE INDEX idx_household_members_hh_person
  ON household_members(household_id, person_id) WHERE person_id IS NOT NULL;
CREATE INDEX idx_household_members_household ON household_members(household_id);

-- person_notes: pastoral notes, admin-only read/write (privacy rule — ministry
-- leaders never see notes). Soft-deleted via deleted_at.
CREATE TABLE person_notes (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  person_id INTEGER NOT NULL REFERENCES people(id),
  author_email TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
);
CREATE INDEX idx_person_notes_person ON person_notes(person_id);
