-- Giving module schema (Supabase-only module).
ALTER TABLE people ADD COLUMN finance INTEGER NOT NULL DEFAULT 0;
ALTER TABLE people ADD COLUMN stripe_customer_id TEXT;

CREATE TABLE funds (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fund_number TEXT NOT NULL UNIQUE,
  active INTEGER NOT NULL DEFAULT 1,
  sort INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE fund_i18n (
  fund_id integer NOT NULL REFERENCES funds(id) ON DELETE CASCADE,
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  name TEXT NOT NULL,
  PRIMARY KEY (fund_id, locale)
);

CREATE TABLE gifts (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  person_id integer REFERENCES people(id) ON DELETE SET NULL,
  donor_name TEXT,
  donor_email TEXT,
  fund_id integer NOT NULL REFERENCES funds(id),
  amount_cents INTEGER NOT NULL CHECK (amount_cents > 0),
  currency TEXT NOT NULL DEFAULT 'usd',
  method TEXT NOT NULL CHECK (method IN ('card','check','cash')),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','succeeded','failed','refunded')),
  stripe_checkout_session_id TEXT,
  stripe_payment_intent_id TEXT,
  stripe_invoice_id TEXT,
  stripe_subscription_id TEXT,
  check_number TEXT,
  received_on TEXT,              -- YYYY-MM-DD; manual check/cash entries
  recorded_by integer REFERENCES people(id) ON DELETE SET NULL,
  note TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
-- Webhook idempotency: each Stripe object materializes at most one gift.
CREATE UNIQUE INDEX gifts_pi ON gifts(stripe_payment_intent_id) WHERE stripe_payment_intent_id IS NOT NULL;
CREATE UNIQUE INDEX gifts_invoice ON gifts(stripe_invoice_id) WHERE stripe_invoice_id IS NOT NULL;
CREATE INDEX gifts_person ON gifts(person_id);
CREATE INDEX gifts_fund_created ON gifts(fund_id, created_at);

CREATE TABLE recurring_gifts (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  person_id integer NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  fund_id integer NOT NULL REFERENCES funds(id),
  amount_cents INTEGER NOT NULL CHECK (amount_cents > 0),
  currency TEXT NOT NULL DEFAULT 'usd',
  "interval" TEXT NOT NULL CHECK ("interval" IN ('week','month')),
  stripe_subscription_id TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active','past_due','canceled')),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX recurring_person ON recurring_gifts(person_id);
