-- Registration module schema (Supabase-only module).
CREATE TABLE reg_events (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  starts_at TEXT NOT NULL,          -- YYYY-MM-DD HH:MM:SS (UTC, like the rest of the app)
  ends_at TEXT,
  location TEXT,
  capacity INTEGER CHECK (capacity IS NULL OR capacity > 0),   -- NULL = unlimited
  price_cents INTEGER CHECK (price_cents IS NULL OR price_cents >= 0), -- NULL/0 = free
  currency TEXT NOT NULL DEFAULT 'usd',
  opens_at TEXT,                    -- NULL = open immediately
  closes_at TEXT,                   -- NULL = open until start
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE reg_event_i18n (
  event_id integer NOT NULL REFERENCES reg_events(id) ON DELETE CASCADE,
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  title TEXT NOT NULL,
  description TEXT,
  PRIMARY KEY (event_id, locale)
);

CREATE TABLE reg_questions (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id integer NOT NULL REFERENCES reg_events(id) ON DELETE CASCADE,
  sort INTEGER NOT NULL DEFAULT 0,
  type TEXT NOT NULL CHECK (type IN ('text','textarea','select','checkbox','yesno')),
  required INTEGER NOT NULL DEFAULT 0,
  options TEXT                       -- JSON array of strings, select/checkbox only
);

CREATE TABLE reg_question_i18n (
  question_id integer NOT NULL REFERENCES reg_questions(id) ON DELETE CASCADE,
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  label TEXT NOT NULL,
  PRIMARY KEY (question_id, locale)
);

CREATE TABLE registrations (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id integer NOT NULL REFERENCES reg_events(id) ON DELETE CASCADE,
  person_id integer REFERENCES people(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','confirmed','cancelled')),
  amount_cents INTEGER NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'usd',
  stripe_checkout_session_id TEXT,
  stripe_payment_intent_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE UNIQUE INDEX registrations_session ON registrations(stripe_checkout_session_id)
  WHERE stripe_checkout_session_id IS NOT NULL;
CREATE INDEX registrations_event ON registrations(event_id, status);

CREATE TABLE reg_answers (
  registration_id integer NOT NULL REFERENCES registrations(id) ON DELETE CASCADE,
  question_id integer NOT NULL REFERENCES reg_questions(id) ON DELETE CASCADE,
  value TEXT NOT NULL,               -- checkbox answers JSON-encoded array
  PRIMARY KEY (registration_id, question_id)
);
