-- Custom pages module (mirrors migrations/0005_custom_pages.sql). id stays a
-- plain TEXT primary key on this backend too — not `integer ... GENERATED BY
-- DEFAULT AS IDENTITY` like the rest of this file — because the id is minted by
-- the app (crypto.randomUUID(), see pagesDb.ts) before the first insert, the
-- same on both backends.
CREATE TABLE custom_pages (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  published INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE custom_page_i18n (
  page_id TEXT NOT NULL REFERENCES custom_pages(id) ON DELETE CASCADE,
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  title TEXT NOT NULL DEFAULT '',
  body_md TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (page_id, locale)
);

-- Widen revisions (migrations-supabase/0001_init.sql) for the new
-- 'custom_page' entity + its TEXT (UUID) ids. Unlike SQLite's affinity-only
-- INTEGER declaration on the D1 side, Postgres enforces column types strictly,
-- so entity_id must actually change type here for a custom_pages id to insert
-- cleanly; existing integer entity_ids round-trip fine as their text form.
ALTER TABLE revisions DROP CONSTRAINT revisions_entity_check;
ALTER TABLE revisions ADD CONSTRAINT revisions_entity_check CHECK (entity IN
  ('bulletin','sermon','prayer_sheet','announcement','event','custom_page'));
ALTER TABLE revisions ALTER COLUMN entity_id TYPE TEXT USING entity_id::text;
