-- Groups module (Postgres port of migrations/0005_groups.sql). IDENTITY ids,
-- otherwise identical to the D1 version incl. datetime('now') defaults (compat
-- functions provide them on Postgres). This file additionally carries the
-- Supabase-only group_reg_events link table (FK to reg_events — the registration
-- module is Supabase-only, so D1 never has that table).

CREATE TABLE groups (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  is_public INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
);

-- person_id NULL = name-only member (household_members precedent; people.email is the auth key).
CREATE TABLE group_members (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id INTEGER NOT NULL REFERENCES groups(id),
  person_id INTEGER REFERENCES people(id),
  display_name TEXT NOT NULL,
  phone TEXT,
  is_admin INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  removed_at TEXT
);
CREATE UNIQUE INDEX idx_group_members_gp ON group_members(group_id, person_id)
  WHERE person_id IS NOT NULL AND removed_at IS NULL;
CREATE INDEX idx_group_members_group ON group_members(group_id);
CREATE INDEX idx_group_members_person ON group_members(person_id);

CREATE TABLE group_join_requests (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id INTEGER NOT NULL REFERENCES groups(id),
  person_id INTEGER NOT NULL REFERENCES people(id),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  decided_at TEXT,
  decided_by INTEGER REFERENCES people(id)
);
CREATE UNIQUE INDEX idx_gjr_pending ON group_join_requests(group_id, person_id) WHERE status = 'pending';
CREATE INDEX idx_gjr_group ON group_join_requests(group_id, status);

-- ROUTINE events (series or one-off). recurrence 'none' = single occurrence at starts_on/start_time.
CREATE TABLE group_events (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id INTEGER NOT NULL REFERENCES groups(id),
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  location TEXT,
  recurrence TEXT NOT NULL DEFAULT 'none' CHECK (recurrence IN ('none','weekly','biweekly','monthly')),
  starts_on TEXT NOT NULL,          -- first occurrence date YYYY-MM-DD (site TZ, America/Chicago like digest.ts)
  start_time TEXT NOT NULL,         -- HH:MM 24h, site TZ
  duration_min INTEGER NOT NULL DEFAULT 90,
  ends_on TEXT,                     -- optional series end date
  track_attendance INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
);
CREATE INDEX idx_group_events_group ON group_events(group_id);

-- Materialized occurrences (planDb ensureWeeklyPlans precedent). starts_at/ends_at are UTC datetimes
-- ('YYYY-MM-DD HH:MM:SS') computed from the local date+time via the site TZ.
CREATE TABLE group_event_occurrences (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id INTEGER NOT NULL REFERENCES group_events(id),
  occurs_on TEXT NOT NULL,
  starts_at TEXT NOT NULL,
  ends_at TEXT NOT NULL,
  attendance_email_sent_at TEXT,    -- cron idempotency claim
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
);
CREATE UNIQUE INDEX idx_geo_event_date ON group_event_occurrences(event_id, occurs_on);
CREATE INDEX idx_geo_ends ON group_event_occurrences(ends_at);

CREATE TABLE group_attendance (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  occurrence_id INTEGER NOT NULL REFERENCES group_event_occurrences(id),
  member_id INTEGER NOT NULL REFERENCES group_members(id),
  present INTEGER NOT NULL DEFAULT 1,
  recorded_by INTEGER REFERENCES people(id),
  recorded_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE UNIQUE INDEX idx_ga_occ_member ON group_attendance(occurrence_id, member_id);

-- Attendance-tracker links. Dedicated table: the shared tokens.purpose CHECK can't be altered in SQLite.
-- Same semantics as tokens: only SHA-256 hex hash at rest, expiring, bound to occurrence+person.
CREATE TABLE group_attendance_tokens (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  occurrence_id INTEGER NOT NULL REFERENCES group_event_occurrences(id),
  person_id INTEGER NOT NULL REFERENCES people(id),
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_gat_occurrence ON group_attendance_tokens(occurrence_id);

-- Supabase-only: link a group to registration events (reg_events lives only on
-- the Postgres backend; callers gate on modules.has('registration')).
CREATE TABLE group_reg_events (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id integer NOT NULL REFERENCES groups(id),
  reg_event_id integer NOT NULL REFERENCES reg_events(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE UNIQUE INDEX idx_gre_pair ON group_reg_events(group_id, reg_event_id);
