-- Children's check-in: kiosk events and per-child check-in records.
-- Mirror of migrations/0007_children_checkin.sql (porting rules: see 0001_init.sql).

CREATE TABLE checkin_events (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  weekday INTEGER CHECK (weekday BETWEEN 0 AND 6),
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE checkins (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id INTEGER NOT NULL REFERENCES checkin_events(id),
  household_id INTEGER NOT NULL REFERENCES households(id),
  household_member_id INTEGER NOT NULL REFERENCES household_members(id),
  child_name TEXT NOT NULL,
  security_code TEXT NOT NULL,
  checkin_date TEXT NOT NULL,
  checked_in_at TEXT NOT NULL DEFAULT (datetime('now')),
  checked_out_at TEXT
);

CREATE UNIQUE INDEX idx_checkins_once_per_day
  ON checkins(event_id, household_member_id, checkin_date);
CREATE INDEX idx_checkins_date ON checkins(checkin_date);
