-- Member portal: mirror of migrations/0007_member_portal.sql plus the
-- Supabase-only portal tables (giving/registration precedent).

ALTER TABLE household_members ADD COLUMN is_owner INTEGER NOT NULL DEFAULT 0;
ALTER TABLE people ADD COLUMN pending_email TEXT;

-- Inline CHECK from 0001_init.sql auto-named tokens_purpose_check.
ALTER TABLE tokens DROP CONSTRAINT tokens_purpose_check;
ALTER TABLE tokens ADD CONSTRAINT tokens_purpose_check
  CHECK (purpose IN ('login','respond','email_change'));

CREATE TABLE member_groups (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug TEXT NOT NULL UNIQUE,
  kind TEXT NOT NULL DEFAULT 'fellowship' CHECK (kind IN ('fellowship','sunday_school')),
  term_label TEXT,
  term_start TEXT,
  term_end TEXT,
  meeting_weekday INTEGER CHECK (meeting_weekday BETWEEN 0 AND 6),
  meeting_time TEXT,
  meeting_frequency TEXT CHECK (meeting_frequency IN ('weekly','biweekly','monthly')),
  meeting_location TEXT,
  open_signup INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  sort INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
);

CREATE TABLE member_group_i18n (
  group_id INTEGER NOT NULL REFERENCES member_groups(id),
  locale TEXT NOT NULL CHECK (locale IN ('en','zh')),
  name TEXT NOT NULL,
  description TEXT,
  PRIMARY KEY (group_id, locale)
);

-- ---- Portal-only (no D1 counterpart) ----

CREATE TABLE group_members (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id INTEGER NOT NULL REFERENCES member_groups(id),
  person_id INTEGER NOT NULL REFERENCES people(id),
  is_leader INTEGER NOT NULL DEFAULT 0,
  joined_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (group_id, person_id)
);

CREATE TABLE group_applications (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id INTEGER NOT NULL REFERENCES member_groups(id),
  person_id INTEGER NOT NULL REFERENCES people(id),
  status TEXT NOT NULL DEFAULT 'P' CHECK (status IN ('P','A','R')),
  note TEXT,
  decided_by INTEGER REFERENCES people(id),
  decided_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_group_applications_pending
  ON group_applications(group_id, status);

CREATE TABLE group_files (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id INTEGER NOT NULL REFERENCES member_groups(id),
  uploaded_by INTEGER NOT NULL REFERENCES people(id),
  file_name TEXT NOT NULL,
  r2_key TEXT NOT NULL UNIQUE,      -- group-files/{group_id}/{random}
  content_type TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
);
CREATE INDEX idx_group_files_group ON group_files(group_id, deleted_at);

CREATE TABLE event_admins (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  reg_event_id INTEGER NOT NULL REFERENCES reg_events(id),
  person_id INTEGER NOT NULL REFERENCES people(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (reg_event_id, person_id)
);

CREATE TABLE prayer_items (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  author_person_id INTEGER NOT NULL REFERENCES people(id),
  scope TEXT NOT NULL CHECK (scope IN ('church','group','event','private')),
  group_id INTEGER REFERENCES member_groups(id),
  reg_event_id INTEGER REFERENCES reg_events(id),
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  approved_by INTEGER REFERENCES people(id),
  approved_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
);
CREATE INDEX idx_prayer_items_scope ON prayer_items(scope, status, deleted_at);
CREATE INDEX idx_prayer_items_group ON prayer_items(group_id);
CREATE INDEX idx_prayer_items_event ON prayer_items(reg_event_id);
