-- Member portal: mirror of migrations/0010_member_portal.sql plus the
-- Supabase-only portal tables (giving/registration precedent). Portal fuses
-- onto the existing groups module, so group_files/prayer_items reference the
-- shared `groups` table (this repo has no member_groups).

ALTER TABLE groups ADD COLUMN kind TEXT NOT NULL DEFAULT 'fellowship'
  CHECK (kind IN ('fellowship','sunday_school'));
ALTER TABLE groups ADD COLUMN term_label TEXT;
ALTER TABLE groups ADD COLUMN term_start TEXT;
ALTER TABLE groups ADD COLUMN term_end TEXT;

ALTER TABLE household_members ADD COLUMN is_owner INTEGER NOT NULL DEFAULT 0;
ALTER TABLE people ADD COLUMN pending_email TEXT;

-- Inline CHECK from 0001_init.sql auto-named tokens_purpose_check.
ALTER TABLE tokens DROP CONSTRAINT tokens_purpose_check;
ALTER TABLE tokens ADD CONSTRAINT tokens_purpose_check
  CHECK (purpose IN ('login','respond','email_change'));

-- ---- Portal-only (no D1 counterpart) ----

CREATE TABLE group_files (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id INTEGER NOT NULL REFERENCES groups(id),
  uploaded_by INTEGER NOT NULL REFERENCES people(id),
  file_name TEXT NOT NULL,
  r2_key TEXT NOT NULL UNIQUE,      -- group-files/{group_id}/{random}
  content_type TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
);
CREATE INDEX idx_group_files_group ON group_files(group_id, deleted_at);

CREATE TABLE event_admins (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  reg_event_id INTEGER NOT NULL REFERENCES reg_events(id),
  person_id INTEGER NOT NULL REFERENCES people(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (reg_event_id, person_id)
);

CREATE TABLE prayer_items (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  author_person_id INTEGER NOT NULL REFERENCES people(id),
  scope TEXT NOT NULL CHECK (scope IN ('church','group','event','private')),
  group_id INTEGER REFERENCES groups(id),
  reg_event_id INTEGER REFERENCES reg_events(id),
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  approved_by INTEGER REFERENCES people(id),
  approved_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
);
CREATE INDEX idx_prayer_items_scope ON prayer_items(scope, status, deleted_at);
CREATE INDEX idx_prayer_items_group ON prayer_items(group_id);
CREATE INDEX idx_prayer_items_event ON prayer_items(reg_event_id);
