-- PostgreSQL parity for migrations/0011_people_exports.sql. Exported contact
-- data and note bodies never enter this structural audit trail.
CREATE TABLE audit_events (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  actor_person_id INTEGER NOT NULL REFERENCES people(id),
  action_kind TEXT NOT NULL
    CHECK (action_kind IN ('people_notes_export_generated')),
  structural_counts_json TEXT NOT NULL
    CHECK (
      length(structural_counts_json) BETWEEN 2 AND 256
      AND jsonb_typeof(structural_counts_json::jsonb) = 'object'
      AND jsonb_typeof((structural_counts_json::jsonb)->'people') = 'number'
      AND jsonb_typeof((structural_counts_json::jsonb)->'notes') = 'number'
      AND (structural_counts_json::jsonb->>'people') ~ '^(0|[1-9][0-9]{0,3})$'
      AND (structural_counts_json::jsonb->>'notes') ~ '^(0|[1-9][0-9]{0,3})$'
      AND (structural_counts_json::jsonb->>'people')::integer BETWEEN 0 AND 5000
      AND (structural_counts_json::jsonb->>'notes')::integer BETWEEN 0 AND 5000
      AND structural_counts_json::jsonb = jsonb_build_object(
        'people', (structural_counts_json::jsonb->>'people')::integer,
        'notes', (structural_counts_json::jsonb->>'notes')::integer
      )
      AND structural_counts_json =
        '{"people":' || (structural_counts_json::jsonb->>'people')
        || ',"notes":' || (structural_counts_json::jsonb->>'notes') || '}'
    ),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_audit_events_actor_created
  ON audit_events(actor_person_id, created_at);
