-- PostgreSQL parity for migrations/0017_learning.sql. Providers remain
-- authoritative for content, submissions, answers, comments, files, and grades.
-- Soft deletion is intentionally limited to connections, programs, and courses;
-- all other rows follow explicit disconnect, Person-deletion, and retention rules.

CREATE TABLE learning_provider_connections (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY CHECK (id BETWEEN 1 AND 2147483647),
  provider TEXT NOT NULL CHECK (provider IN ('google_classroom','canvas')),
  display_name TEXT NOT NULL
    CHECK (display_name = trim(display_name) AND octet_length(display_name) BETWEEN 1 AND 120),
  base_url TEXT CHECK (
    base_url IS NULL OR (
      base_url = trim(base_url) AND octet_length(base_url) BETWEEN 9 AND 2048 AND
      left(base_url,8) = 'https://' AND position('@' in substr(base_url,9)) = 0 AND
      position('?' in base_url) = 0 AND position('#' in base_url) = 0 AND right(base_url,1) <> '/'
    )
  ),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','active','error','disabled')),
  revision INTEGER NOT NULL DEFAULT 0 CHECK (revision BETWEEN 0 AND 2147483647),
  operation_marker TEXT CHECK (operation_marker IS NULL OR length(operation_marker) = 36),
  last_successful_sync_at TEXT
    CHECK (last_successful_sync_at IS NULL OR octet_length(last_successful_sync_at) BETWEEN 19 AND 40),
  last_error_code TEXT
    CHECK (last_error_code IS NULL OR (octet_length(last_error_code) BETWEEN 1 AND 64 AND last_error_code ~ '^[a-z][a-z0-9_]*$')),
  created_by_person_id INTEGER REFERENCES people(id) ON DELETE SET NULL,
  updated_by_person_id INTEGER REFERENCES people(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(created_at) BETWEEN 19 AND 40),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(updated_at) BETWEEN 19 AND 40),
  deleted_at TEXT CHECK (deleted_at IS NULL OR octet_length(deleted_at) BETWEEN 19 AND 40),
  UNIQUE (id, provider),
  UNIQUE (provider, base_url),
  CHECK (
    (provider = 'google_classroom' AND base_url IS NULL) OR
    (provider = 'canvas' AND base_url IS NOT NULL)
  ),
  CHECK (deleted_at IS NULL OR status = 'disabled')
);

CREATE INDEX idx_learning_connections_active_sync
  ON learning_provider_connections(provider, status, last_successful_sync_at, id)
  WHERE deleted_at IS NULL;

-- One current encrypted envelope per connection; there is no plaintext
-- token/code/secret carrier.
CREATE TABLE learning_provider_credentials (
  connection_id INTEGER PRIMARY KEY
    REFERENCES learning_provider_connections(id) ON DELETE CASCADE,
  ciphertext bytea NOT NULL CHECK (octet_length(ciphertext) BETWEEN 16 AND 16384),
  nonce bytea NOT NULL CHECK (octet_length(nonce) BETWEEN 12 AND 32),
  algorithm TEXT NOT NULL CHECK (algorithm = 'AES-256-GCM'),
  key_version INTEGER NOT NULL CHECK (key_version BETWEEN 1 AND 2147483647),
  envelope_version INTEGER NOT NULL DEFAULT 1 CHECK (envelope_version IN (1,2)),
  expires_at TEXT CHECK (expires_at IS NULL OR octet_length(expires_at) BETWEEN 19 AND 40),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(updated_at) BETWEEN 19 AND 40)
);

CREATE TABLE learning_programs (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY CHECK (id BETWEEN 1 AND 2147483647),
  slug TEXT NOT NULL UNIQUE
    CHECK (octet_length(slug) BETWEEN 1 AND 64 AND slug ~ '^[a-z][a-z0-9-]*$'),
  display_name TEXT NOT NULL
    CHECK (display_name = trim(display_name) AND octet_length(display_name) BETWEEN 1 AND 200),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived')),
  created_by_person_id INTEGER REFERENCES people(id) ON DELETE SET NULL,
  updated_by_person_id INTEGER REFERENCES people(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(created_at) BETWEEN 19 AND 40),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(updated_at) BETWEEN 19 AND 40),
  deleted_at TEXT CHECK (deleted_at IS NULL OR octet_length(deleted_at) BETWEEN 19 AND 40),
  CHECK (deleted_at IS NULL OR status = 'archived')
);

CREATE INDEX idx_learning_programs_active_name
  ON learning_programs(status, display_name, id)
  WHERE deleted_at IS NULL;

CREATE TABLE learning_courses (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY CHECK (id BETWEEN 1 AND 2147483647),
  program_id INTEGER NOT NULL REFERENCES learning_programs(id) ON DELETE RESTRICT,
  connection_id INTEGER NOT NULL,
  provider TEXT NOT NULL CHECK (provider IN ('google_classroom','canvas')),
  external_course_id TEXT NOT NULL CHECK (
    external_course_id = trim(external_course_id) AND octet_length(external_course_id) BETWEEN 1 AND 255
  ),
  display_name TEXT NOT NULL
    CHECK (display_name = trim(display_name) AND octet_length(display_name) BETWEEN 1 AND 200),
  launch_url TEXT NOT NULL CHECK (
    launch_url = trim(launch_url) AND octet_length(launch_url) BETWEEN 9 AND 2048 AND
    left(launch_url,8) = 'https://' AND position('@' in substr(launch_url,9)) = 0 AND
    position('#' in launch_url) = 0
  ),
  lifecycle_state TEXT NOT NULL DEFAULT 'active'
    CHECK (lifecycle_state IN ('active','archived','deleted')),
  provider_updated_at TEXT
    CHECK (provider_updated_at IS NULL OR octet_length(provider_updated_at) BETWEEN 19 AND 40),
  last_synced_at TEXT CHECK (last_synced_at IS NULL OR octet_length(last_synced_at) BETWEEN 19 AND 40),
  created_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(created_at) BETWEEN 19 AND 40),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(updated_at) BETWEEN 19 AND 40),
  deleted_at TEXT CHECK (deleted_at IS NULL OR octet_length(deleted_at) BETWEEN 19 AND 40),
  UNIQUE (id, connection_id),
  UNIQUE (connection_id, external_course_id),
  FOREIGN KEY (connection_id, provider)
    REFERENCES learning_provider_connections(id, provider) ON DELETE RESTRICT,
  CHECK (deleted_at IS NULL OR lifecycle_state IN ('archived','deleted'))
);

CREATE INDEX idx_learning_courses_program_state
  ON learning_courses(program_id, lifecycle_state, display_name, id)
  WHERE deleted_at IS NULL;
CREATE INDEX idx_learning_courses_connection_sync
  ON learning_courses(connection_id, lifecycle_state, last_synced_at, id)
  WHERE deleted_at IS NULL;

CREATE TABLE learning_identity_links (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY CHECK (id BETWEEN 1 AND 2147483647),
  connection_id INTEGER NOT NULL
    REFERENCES learning_provider_connections(id) ON DELETE RESTRICT,
  person_id INTEGER NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  external_user_id TEXT NOT NULL CHECK (
    external_user_id = trim(external_user_id) AND octet_length(external_user_id) BETWEEN 1 AND 255
  ),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled','conflict')),
  created_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(created_at) BETWEEN 19 AND 40),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(updated_at) BETWEEN 19 AND 40),
  UNIQUE (id, connection_id),
  UNIQUE (id, connection_id, person_id),
  UNIQUE (connection_id, external_user_id),
  UNIQUE (connection_id, person_id)
);

CREATE INDEX idx_learning_identities_person_status
  ON learning_identity_links(person_id, status, id);

CREATE TABLE learning_enrollments (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY CHECK (id BETWEEN 1 AND 2147483647),
  connection_id INTEGER NOT NULL,
  course_id INTEGER NOT NULL,
  identity_link_id INTEGER NOT NULL,
  external_enrollment_id TEXT NOT NULL CHECK (
    external_enrollment_id = trim(external_enrollment_id) AND octet_length(external_enrollment_id) BETWEEN 1 AND 255
  ),
  role TEXT NOT NULL CHECK (role IN ('student','teacher','observer')),
  state TEXT NOT NULL DEFAULT 'active' CHECK (state IN ('active','invited','completed','inactive')),
  last_synced_at TEXT CHECK (last_synced_at IS NULL OR octet_length(last_synced_at) BETWEEN 19 AND 40),
  created_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(created_at) BETWEEN 19 AND 40),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(updated_at) BETWEEN 19 AND 40),
  UNIQUE (id, course_id),
  UNIQUE (id, course_id, connection_id, identity_link_id),
  UNIQUE (course_id, identity_link_id),
  UNIQUE (course_id, external_enrollment_id),
  FOREIGN KEY (course_id, connection_id)
    REFERENCES learning_courses(id, connection_id) ON DELETE CASCADE,
  FOREIGN KEY (identity_link_id, connection_id)
    REFERENCES learning_identity_links(id, connection_id) ON DELETE CASCADE
);

CREATE INDEX idx_learning_enrollments_course_state
  ON learning_enrollments(course_id, state, role, id);
CREATE INDEX idx_learning_enrollments_identity_state
  ON learning_enrollments(identity_link_id, state, course_id, id);

CREATE TABLE learning_activities (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY CHECK (id BETWEEN 1 AND 2147483647),
  course_id INTEGER NOT NULL REFERENCES learning_courses(id) ON DELETE CASCADE,
  external_activity_id TEXT NOT NULL CHECK (
    external_activity_id = trim(external_activity_id) AND octet_length(external_activity_id) BETWEEN 1 AND 255
  ),
  title TEXT NOT NULL CHECK (title = trim(title) AND octet_length(title) BETWEEN 1 AND 300),
  kind TEXT NOT NULL CHECK (kind IN ('material','assignment','quiz')),
  lifecycle_state TEXT NOT NULL DEFAULT 'published'
    CHECK (lifecycle_state IN ('draft','published','archived','deleted')),
  launch_url TEXT NOT NULL CHECK (
    launch_url = trim(launch_url) AND octet_length(launch_url) BETWEEN 9 AND 2048 AND
    left(launch_url,8) = 'https://' AND position('@' in substr(launch_url,9)) = 0 AND
    position('#' in launch_url) = 0
  ),
  due_at TEXT CHECK (due_at IS NULL OR octet_length(due_at) BETWEEN 19 AND 40),
  published_at TEXT CHECK (published_at IS NULL OR octet_length(published_at) BETWEEN 19 AND 40),
  provider_updated_at TEXT
    CHECK (provider_updated_at IS NULL OR octet_length(provider_updated_at) BETWEEN 19 AND 40),
  last_synced_at TEXT CHECK (last_synced_at IS NULL OR octet_length(last_synced_at) BETWEEN 19 AND 40),
  created_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(created_at) BETWEEN 19 AND 40),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(updated_at) BETWEEN 19 AND 40),
  UNIQUE (id, course_id),
  UNIQUE (id, course_id, kind),
  UNIQUE (course_id, external_activity_id)
);

CREATE INDEX idx_learning_activities_course_due
  ON learning_activities(course_id, lifecycle_state, due_at, id);
CREATE INDEX idx_learning_activities_course_kind
  ON learning_activities(course_id, kind, provider_updated_at, id);

-- Direct activity purges are a retention operation. They are permitted only
-- after the owning course is soft-deleted or its connection is disabled/deleted;
-- hard course deletion still cascades through the foreign key.
CREATE OR REPLACE FUNCTION learning_activities_no_delete_fn()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM learning_courses
    WHERE id = OLD.course_id AND deleted_at IS NULL AND EXISTS (
      SELECT 1 FROM learning_provider_connections
      WHERE id = learning_courses.connection_id AND deleted_at IS NULL AND status <> 'disabled'
    )
  ) THEN
    RAISE EXCEPTION 'learning_activity_active_parent' USING ERRCODE = '23514';
  END IF;
  RETURN OLD;
END;
$$;
CREATE TRIGGER learning_activities_no_delete
BEFORE DELETE ON learning_activities FOR EACH ROW
EXECUTE FUNCTION learning_activities_no_delete_fn();

CREATE TABLE learning_resources (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY CHECK (id BETWEEN 1 AND 2147483647),
  activity_id INTEGER NOT NULL REFERENCES learning_activities(id) ON DELETE CASCADE,
  external_resource_id TEXT NOT NULL CHECK (
    external_resource_id = trim(external_resource_id) AND octet_length(external_resource_id) BETWEEN 1 AND 255
  ),
  title TEXT NOT NULL CHECK (title = trim(title) AND octet_length(title) BETWEEN 1 AND 300),
  kind TEXT NOT NULL CHECK (kind IN ('youtube','provider_file','link')),
  launch_url TEXT NOT NULL CHECK (
    launch_url = trim(launch_url) AND octet_length(launch_url) BETWEEN 9 AND 2048 AND
    left(launch_url,8) = 'https://' AND position('@' in substr(launch_url,9)) = 0 AND
    position('#' in launch_url) = 0
  ),
  youtube_video_id TEXT
    CHECK (youtube_video_id IS NULL OR youtube_video_id ~ '^[A-Za-z0-9_-]{11}$'),
  mime_type TEXT CHECK (
    mime_type IS NULL OR (mime_type = trim(mime_type) AND octet_length(mime_type) BETWEEN 1 AND 127)
  ),
  size_bytes INTEGER CHECK (size_bytes BETWEEN 0 AND 2147483647),
  provider_updated_at TEXT
    CHECK (provider_updated_at IS NULL OR octet_length(provider_updated_at) BETWEEN 19 AND 40),
  created_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(created_at) BETWEEN 19 AND 40),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(updated_at) BETWEEN 19 AND 40),
  UNIQUE (activity_id, external_resource_id),
  CHECK (
    (kind = 'youtube' AND youtube_video_id IS NOT NULL AND mime_type IS NULL AND size_bytes IS NULL) OR
    (kind = 'provider_file' AND youtube_video_id IS NULL) OR
    (kind = 'link' AND youtube_video_id IS NULL AND mime_type IS NULL AND size_bytes IS NULL)
  )
);

CREATE INDEX idx_learning_resources_activity_kind
  ON learning_resources(activity_id, kind, id);

-- Current state only: no grade, answer, comment, rubric, title, or file carrier.
CREATE TABLE learning_submission_snapshots (
  course_id INTEGER NOT NULL,
  activity_id INTEGER NOT NULL,
  activity_kind TEXT NOT NULL CHECK (activity_kind IN ('assignment','quiz')),
  enrollment_id INTEGER NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('not_submitted','submitted','returned','excused')),
  late INTEGER NOT NULL DEFAULT 0 CHECK (late IN (0,1)),
  attempt_number INTEGER NOT NULL DEFAULT 0 CHECK (attempt_number BETWEEN 0 AND 1000),
  submitted_at TEXT CHECK (submitted_at IS NULL OR octet_length(submitted_at) BETWEEN 19 AND 40),
  returned_at TEXT CHECK (returned_at IS NULL OR octet_length(returned_at) BETWEEN 19 AND 40),
  provider_updated_at TEXT
    CHECK (provider_updated_at IS NULL OR octet_length(provider_updated_at) BETWEEN 19 AND 40),
  synced_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(synced_at) BETWEEN 19 AND 40),
  PRIMARY KEY (activity_id, enrollment_id),
  FOREIGN KEY (activity_id, course_id, activity_kind)
    REFERENCES learning_activities(id, course_id, kind) ON DELETE CASCADE,
  FOREIGN KEY (enrollment_id, course_id)
    REFERENCES learning_enrollments(id, course_id) ON DELETE CASCADE
);

CREATE INDEX idx_learning_snapshots_enrollment_state
  ON learning_submission_snapshots(enrollment_id, status, synced_at, activity_id);
CREATE INDEX idx_learning_snapshots_course_state
  ON learning_submission_snapshots(course_id, status, late, synced_at, activity_id);

-- Append-only normalized evidence. Stable Person, identity-link, and enrollment
-- identifiers are bound together declaratively so parent reassignment cannot
-- reattribute an event. IDs, allowlisted type, references, and times are the
-- complete event shape; raw payloads and display/content fields are absent.
CREATE TABLE learning_activity_events (
  id TEXT NOT NULL PRIMARY KEY
    CHECK (id = trim(id) AND octet_length(id) BETWEEN 1 AND 255),
  connection_id INTEGER NOT NULL,
  provider TEXT NOT NULL CHECK (provider IN ('google_classroom','canvas')),
  source_event_id TEXT NOT NULL CHECK (
    source_event_id = trim(source_event_id) AND octet_length(source_event_id) BETWEEN 1 AND 255
  ),
  event_type TEXT NOT NULL CHECK (event_type IN (
    'enrolled','resource_opened','assignment_submitted','quiz_submitted',
    'submission_returned','course_completed'
  )),
  person_id INTEGER NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  identity_link_id INTEGER NOT NULL,
  enrollment_id INTEGER NOT NULL,
  course_id INTEGER NOT NULL,
  activity_id INTEGER,
  activity_kind TEXT CHECK (
    activity_kind IS NULL OR activity_kind IN ('material','assignment','quiz')
  ),
  occurred_at TEXT NOT NULL CHECK (octet_length(occurred_at) BETWEEN 19 AND 40),
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(ingested_at) BETWEEN 19 AND 40),
  UNIQUE (connection_id, source_event_id),
  FOREIGN KEY (connection_id, provider)
    REFERENCES learning_provider_connections(id, provider) ON DELETE RESTRICT,
  FOREIGN KEY (course_id, connection_id)
    REFERENCES learning_courses(id, connection_id) ON DELETE CASCADE,
  FOREIGN KEY (identity_link_id, connection_id, person_id)
    REFERENCES learning_identity_links(id, connection_id, person_id) ON DELETE NO ACTION,
  FOREIGN KEY (enrollment_id, course_id, connection_id, identity_link_id)
    REFERENCES learning_enrollments(id, course_id, connection_id, identity_link_id)
    ON DELETE NO ACTION,
  FOREIGN KEY (activity_id, course_id, activity_kind)
    REFERENCES learning_activities(id, course_id, kind) ON DELETE CASCADE,
  CHECK (
    (event_type IN ('enrolled','course_completed') AND
      activity_id IS NULL AND activity_kind IS NULL) OR
    (event_type = 'resource_opened' AND
      activity_id IS NOT NULL AND activity_kind IN ('material','assignment','quiz')) OR
    (event_type = 'assignment_submitted' AND
      activity_id IS NOT NULL AND activity_kind = 'assignment') OR
    (event_type = 'quiz_submitted' AND
      activity_id IS NOT NULL AND activity_kind = 'quiz') OR
    (event_type = 'submission_returned' AND
      activity_id IS NOT NULL AND activity_kind IN ('assignment','quiz'))
  )
);

CREATE INDEX idx_learning_events_enrollment_time
  ON learning_activity_events(enrollment_id, occurred_at, id);
CREATE INDEX idx_learning_events_person_time
  ON learning_activity_events(person_id, occurred_at, id);
CREATE INDEX idx_learning_events_course_time
  ON learning_activity_events(course_id, occurred_at, id);
CREATE INDEX idx_learning_events_activity_time
  ON learning_activity_events(activity_id, occurred_at, id)
  WHERE activity_id IS NOT NULL;
CREATE INDEX idx_learning_events_connection_ingested
  ON learning_activity_events(connection_id, ingested_at, id);

CREATE OR REPLACE FUNCTION learning_activity_events_no_update_fn()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'learning_event_append_only' USING ERRCODE = '23514';
END;
$$;
CREATE TRIGGER learning_activity_events_no_update
BEFORE UPDATE ON learning_activity_events FOR EACH ROW
EXECUTE FUNCTION learning_activity_events_no_update_fn();

CREATE OR REPLACE FUNCTION learning_activity_events_no_delete_fn()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF
    EXISTS (SELECT 1 FROM people WHERE id = OLD.person_id) AND
    EXISTS (SELECT 1 FROM learning_identity_links WHERE id = OLD.identity_link_id) AND
    EXISTS (SELECT 1 FROM learning_enrollments WHERE id = OLD.enrollment_id) AND
    EXISTS (SELECT 1 FROM learning_courses WHERE id = OLD.course_id AND deleted_at IS NULL) AND
    EXISTS (SELECT 1 FROM learning_provider_connections
      WHERE id = OLD.connection_id AND deleted_at IS NULL AND status <> 'disabled')
  THEN
    RAISE EXCEPTION 'learning_event_append_only' USING ERRCODE = '23514';
  END IF;
  RETURN OLD;
END;
$$;
CREATE TRIGGER learning_activity_events_no_delete
BEFORE DELETE ON learning_activity_events FOR EACH ROW
EXECUTE FUNCTION learning_activity_events_no_delete_fn();

-- Bounded operational facts only; no provider response, URL, name, token, or
-- submission carrier is permitted in a run row.
CREATE TABLE learning_sync_runs (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY CHECK (id BETWEEN 1 AND 2147483647),
  connection_id INTEGER NOT NULL,
  course_id INTEGER,
  trigger_type TEXT NOT NULL CHECK (trigger_type IN ('manual','scheduled','notification')),
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running','succeeded','failed','cancelled')),
  started_at TEXT NOT NULL DEFAULT (datetime('now')) CHECK (octet_length(started_at) BETWEEN 19 AND 40),
  finished_at TEXT CHECK (finished_at IS NULL OR octet_length(finished_at) BETWEEN 19 AND 40),
  attempt_count INTEGER NOT NULL DEFAULT 1 CHECK (attempt_count BETWEEN 1 AND 10),
  scanned_count INTEGER NOT NULL DEFAULT 0 CHECK (scanned_count BETWEEN 0 AND 100000),
  changed_count INTEGER NOT NULL DEFAULT 0 CHECK (changed_count BETWEEN 0 AND 100000),
  removed_count INTEGER NOT NULL DEFAULT 0 CHECK (removed_count BETWEEN 0 AND 100000),
  event_count INTEGER NOT NULL DEFAULT 0 CHECK (event_count BETWEEN 0 AND 100000),
  error_code TEXT CHECK (
    error_code IS NULL OR (octet_length(error_code) BETWEEN 1 AND 64 AND error_code ~ '^[a-z][a-z0-9_]*$')
  ),
  FOREIGN KEY (connection_id) REFERENCES learning_provider_connections(id) ON DELETE RESTRICT,
  FOREIGN KEY (course_id, connection_id)
    REFERENCES learning_courses(id, connection_id) ON DELETE RESTRICT,
  CHECK (
    (status = 'running' AND finished_at IS NULL AND error_code IS NULL) OR
    (status = 'succeeded' AND finished_at IS NOT NULL AND error_code IS NULL) OR
    (status = 'failed' AND finished_at IS NOT NULL AND error_code IS NOT NULL) OR
    (status = 'cancelled' AND finished_at IS NOT NULL AND error_code IS NULL)
  )
);

CREATE INDEX idx_learning_sync_runs_connection_time
  ON learning_sync_runs(connection_id, started_at, id);
CREATE INDEX idx_learning_sync_runs_course_time
  ON learning_sync_runs(course_id, started_at, id)
  WHERE course_id IS NOT NULL;
CREATE INDEX idx_learning_sync_runs_status_time
  ON learning_sync_runs(status, started_at, id);

-- Learning integration metadata is server-only. No browser-facing RLS policies
-- are defined; service/backend owners retain normal owner access.
ALTER TABLE learning_provider_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_provider_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_identity_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_submission_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_activity_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_sync_runs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE
  learning_provider_connections,
  learning_provider_credentials,
  learning_programs,
  learning_courses,
  learning_identity_links,
  learning_enrollments,
  learning_activities,
  learning_resources,
  learning_submission_snapshots,
  learning_activity_events,
  learning_sync_runs
FROM PUBLIC;

DO $$
DECLARE
  client_role text;
BEGIN
  FOREACH client_role IN ARRAY ARRAY['anon','authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = client_role) THEN
      EXECUTE format('REVOKE ALL ON TABLE
        learning_provider_connections,
        learning_provider_credentials,
        learning_programs,
        learning_courses,
        learning_identity_links,
        learning_enrollments,
        learning_activities,
        learning_resources,
        learning_submission_snapshots,
        learning_activity_events,
        learning_sync_runs
      FROM %I', client_role);
    END IF;
  END LOOP;
END
$$;
