-- PostgreSQL parity for migrations/0031_identity_source_records.sql. The
-- stable source-key HMAC configuration is immutable; rotation requires an
-- explicit future transactional rewrap instead of replacing a secret in place.

CREATE TABLE identity_source_key_config (
  singleton_id INTEGER PRIMARY KEY CHECK (singleton_id=1),
  key_id TEXT NOT NULL UNIQUE CHECK (octet_length(key_id) BETWEEN 1 AND 32 AND key_id ~ '^[a-z0-9][a-z0-9._-]{0,31}$'),
  algorithm_version INTEGER NOT NULL CHECK (algorithm_version=1),
  verification_tag TEXT NOT NULL CHECK (octet_length(verification_tag)=64 AND verification_tag ~ '^[0-9a-f]{64}$'),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE identity_source_records (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  campus_id INTEGER NOT NULL DEFAULT 1 REFERENCES campuses(id),
  source TEXT NOT NULL CHECK (source IN ('giving','registration','group','team','newcomer','import','planning_center')),
  source_record_key TEXT NOT NULL CHECK (octet_length(source_record_key)=64 AND source_record_key ~ '^[0-9a-f]{64}$'),
  source_key_id TEXT NOT NULL REFERENCES identity_source_key_config(key_id),
  observation_id INTEGER NOT NULL UNIQUE REFERENCES identity_observations(id),
  attachment_policy TEXT NOT NULL CHECK (attachment_policy IN ('signed_in_or_claim','observation_only','external_review')),
  linked_person_id INTEGER REFERENCES people(id),
  provisional_person_id INTEGER UNIQUE REFERENCES people(id),
  state TEXT NOT NULL DEFAULT 'unlinked' CHECK (state IN ('unlinked','linked','review')),
  version INTEGER NOT NULL DEFAULT 1 CHECK (version BETWEEN 1 AND 2147483647),
  source_digest TEXT NOT NULL CHECK (octet_length(source_digest)=64 AND source_digest ~ '^[0-9a-f]{64}$'),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (campus_id,source,source_record_key),
  CHECK ((state='linked')=(linked_person_id IS NOT NULL)),
  CHECK (linked_person_id IS NULL OR linked_person_id<>provisional_person_id),
  CHECK ((source IN ('giving','registration','team') AND attachment_policy='signed_in_or_claim')
    OR (source IN ('group','newcomer','import') AND attachment_policy='observation_only')
    OR (source='planning_center' AND attachment_policy='external_review'))
);
CREATE INDEX idx_identity_source_records_queue ON identity_source_records(campus_id,state,source,created_at);
CREATE INDEX idx_identity_source_records_person ON identity_source_records(linked_person_id,source);

CREATE OR REPLACE FUNCTION identity_source_key_config_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'identity_source_key_config_immutable'; END;
$$;
CREATE TRIGGER identity_source_key_config_immutable_update BEFORE UPDATE ON identity_source_key_config
FOR EACH ROW EXECUTE FUNCTION identity_source_key_config_immutable();
CREATE TRIGGER identity_source_key_config_immutable_delete BEFORE DELETE ON identity_source_key_config
FOR EACH ROW EXECUTE FUNCTION identity_source_key_config_immutable();

CREATE TABLE identity_source_provisional_operations (
  operation_id TEXT PRIMARY KEY CHECK (octet_length(operation_id)=36 AND operation_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'),
  campus_id INTEGER NOT NULL DEFAULT 1 REFERENCES campuses(id),
  source_record_id INTEGER NOT NULL UNIQUE REFERENCES identity_source_records(id),
  source_version INTEGER NOT NULL CHECK (source_version BETWEEN 1 AND 2147483647),
  source_digest TEXT NOT NULL CHECK (octet_length(source_digest)=64 AND source_digest ~ '^[0-9a-f]{64}$'),
  reserved_person_id INTEGER NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE identity_source_provisional_receipts (
  receipt_id TEXT PRIMARY KEY CHECK (octet_length(receipt_id)=36 AND receipt_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'),
  campus_id INTEGER NOT NULL DEFAULT 1 REFERENCES campuses(id),
  operation_id TEXT NOT NULL UNIQUE REFERENCES identity_source_provisional_operations(operation_id),
  source_record_id INTEGER NOT NULL UNIQUE REFERENCES identity_source_records(id),
  source_version INTEGER NOT NULL CHECK (source_version BETWEEN 1 AND 2147483647),
  source_digest TEXT NOT NULL CHECK (octet_length(source_digest)=64 AND source_digest ~ '^[0-9a-f]{64}$'),
  person_id INTEGER NOT NULL UNIQUE REFERENCES people(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE identity_claim_operations (
  operation_id TEXT PRIMARY KEY CHECK (octet_length(operation_id)=36 AND operation_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'),
  campus_id INTEGER NOT NULL DEFAULT 1 REFERENCES campuses(id),
  source_record_id INTEGER NOT NULL REFERENCES identity_source_records(id),
  challenge_id INTEGER NOT NULL UNIQUE REFERENCES identity_challenges(id),
  expected_source_version INTEGER NOT NULL CHECK (expected_source_version BETWEEN 1 AND 2147483647),
  expected_source_digest TEXT NOT NULL CHECK (octet_length(expected_source_digest)=64 AND expected_source_digest ~ '^[0-9a-f]{64}$'),
  expected_contact_point_id INTEGER NOT NULL REFERENCES contact_points(id),
  expected_owner_person_id INTEGER REFERENCES people(id),
  expected_owner_generation INTEGER CHECK (expected_owner_generation IS NULL OR expected_owner_generation BETWEEN 0 AND 2147483647),
  state TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','review','completed','expired')),
  result_person_id INTEGER REFERENCES people(id),
  result_proof_kind TEXT CHECK (result_proof_kind IS NULL OR result_proof_kind IN ('claim_owner','clean_signup')),
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  CHECK ((expected_owner_person_id IS NULL)=(expected_owner_generation IS NULL)),
  CHECK ((state='completed')=(result_person_id IS NOT NULL)),
  CHECK ((result_person_id IS NULL)=(result_proof_kind IS NULL))
);
CREATE INDEX idx_identity_claim_operations_source_state ON identity_claim_operations(campus_id,source_record_id,state,created_at);

CREATE TABLE identity_source_attachment_receipts (
  receipt_id TEXT PRIMARY KEY CHECK (octet_length(receipt_id)=36 AND receipt_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'),
  campus_id INTEGER NOT NULL DEFAULT 1 REFERENCES campuses(id),
  source_record_id INTEGER NOT NULL UNIQUE REFERENCES identity_source_records(id),
  source_version INTEGER NOT NULL CHECK (source_version BETWEEN 1 AND 2147483647),
  source_digest TEXT NOT NULL CHECK (octet_length(source_digest)=64 AND source_digest ~ '^[0-9a-f]{64}$'),
  person_id INTEGER NOT NULL REFERENCES people(id),
  proof_kind TEXT NOT NULL CHECK (proof_kind IN ('signed_session','claim_owner','clean_signup')),
  claim_operation_id TEXT UNIQUE REFERENCES identity_claim_operations(operation_id),
  challenge_id INTEGER UNIQUE REFERENCES identity_challenges(id),
  contact_point_id INTEGER REFERENCES contact_points(id),
  signup_account_operation_id TEXT REFERENCES identity_account_operations(operation_id),
  session_epoch INTEGER CHECK (session_epoch IS NULL OR session_epoch BETWEEN 0 AND 2147483647),
  owner_generation INTEGER CHECK (owner_generation IS NULL OR owner_generation BETWEEN 0 AND 2147483647),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  CHECK ((proof_kind='signed_session' AND claim_operation_id IS NULL AND challenge_id IS NULL AND contact_point_id IS NULL
      AND signup_account_operation_id IS NULL AND session_epoch IS NOT NULL AND owner_generation IS NULL)
    OR (proof_kind='claim_owner' AND claim_operation_id IS NOT NULL AND challenge_id IS NOT NULL AND contact_point_id IS NOT NULL
      AND signup_account_operation_id IS NULL AND session_epoch IS NULL AND owner_generation IS NOT NULL)
    OR (proof_kind='clean_signup' AND claim_operation_id IS NOT NULL AND challenge_id IS NOT NULL AND contact_point_id IS NOT NULL
      AND signup_account_operation_id IS NOT NULL AND session_epoch IS NULL AND owner_generation IS NULL))
);
CREATE INDEX idx_identity_source_receipts_person ON identity_source_attachment_receipts(person_id,created_at);

CREATE TABLE identity_source_attachment_commits (
  commit_id TEXT PRIMARY KEY CHECK (octet_length(commit_id)=36 AND commit_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'),
  campus_id INTEGER NOT NULL DEFAULT 1 REFERENCES campuses(id),
  receipt_id TEXT NOT NULL UNIQUE REFERENCES identity_source_attachment_receipts(receipt_id),
  source_record_id INTEGER NOT NULL UNIQUE REFERENCES identity_source_records(id),
  person_id INTEGER NOT NULL REFERENCES people(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE OR REPLACE FUNCTION identity_source_records_insert_unlinked() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.linked_person_id IS NOT NULL OR NEW.provisional_person_id IS NOT NULL OR NEW.state<>'unlinked' OR NOT EXISTS (
    SELECT 1 FROM identity_observations o WHERE o.id=NEW.observation_id AND o.campus_id=NEW.campus_id
      AND o.source=NEW.source AND o.source_key=NEW.source_record_key AND o.status='provisional' AND o.linked_person_id IS NULL
  ) OR NOT EXISTS (
    SELECT 1 FROM identity_source_key_config k WHERE k.singleton_id=1 AND k.key_id=NEW.source_key_id
  ) THEN RAISE EXCEPTION 'identity_source_insert_invalid'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_source_records_insert_unlinked BEFORE INSERT ON identity_source_records FOR EACH ROW EXECUTE FUNCTION identity_source_records_insert_unlinked();

CREATE OR REPLACE FUNCTION identity_source_records_identity_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.campus_id<>NEW.campus_id OR OLD.source<>NEW.source OR OLD.source_record_key<>NEW.source_record_key
    OR OLD.source_key_id<>NEW.source_key_id OR OLD.observation_id<>NEW.observation_id OR OLD.attachment_policy<>NEW.attachment_policy
  THEN RAISE EXCEPTION 'identity_source_identity_immutable'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_source_records_identity_immutable BEFORE UPDATE OF campus_id,source,source_record_key,source_key_id,observation_id,attachment_policy ON identity_source_records FOR EACH ROW EXECUTE FUNCTION identity_source_records_identity_immutable();

CREATE OR REPLACE FUNCTION identity_source_records_version_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF (NEW.version<>OLD.version OR NEW.source_digest<>OLD.source_digest) AND (
    OLD.state='linked' OR NEW.version<>OLD.version+1 OR NEW.source_digest=OLD.source_digest OR NEW.state<>'unlinked'
    OR NEW.linked_person_id IS NOT NULL OR OLD.provisional_person_id IS NOT NULL OR EXISTS (
      SELECT 1 FROM identity_source_provisional_operations op
      WHERE op.source_record_id=OLD.id AND op.source_version=OLD.version AND op.source_digest=OLD.source_digest
    )
  ) THEN RAISE EXCEPTION 'identity_source_version_conflict'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_source_records_version_guard BEFORE UPDATE OF version,source_digest ON identity_source_records FOR EACH ROW EXECUTE FUNCTION identity_source_records_version_guard();

CREATE OR REPLACE FUNCTION identity_claim_operation_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM identity_source_records s JOIN identity_observations o ON o.id=s.observation_id
    JOIN contact_points cp ON cp.id=NEW.expected_contact_point_id
    WHERE s.id=NEW.source_record_id AND s.campus_id=NEW.campus_id AND s.attachment_policy='signed_in_or_claim'
      AND s.state='unlinked' AND s.version=NEW.expected_source_version AND s.source_digest=NEW.expected_source_digest
      AND cp.kind='email' AND cp.normalized_value=o.normalized_email
  ) OR NOT EXISTS (
    SELECT 1 FROM identity_challenges c WHERE c.id=NEW.challenge_id AND c.campus_id=NEW.campus_id
      AND c.purpose='claim' AND c.contact_point_id=NEW.expected_contact_point_id AND c.consumed_at IS NULL AND c.superseded_at IS NULL
      AND c.expires_at>datetime('now') AND (NEW.expected_owner_person_id IS NULL OR c.person_id=NEW.expected_owner_person_id)
  ) OR (NEW.expected_owner_person_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM verified_contact_owners v JOIN people p ON p.id=v.person_id
    JOIN campus_memberships cm ON cm.person_id=p.id AND cm.campus_id=NEW.campus_id AND cm.active=1
    LEFT JOIN person_merge_redirects r ON r.loser_person_id=p.id
    WHERE v.contact_point_id=NEW.expected_contact_point_id AND v.person_id=NEW.expected_owner_person_id
      AND NEW.expected_owner_generation=COALESCE((SELECT MAX(generation) FROM contact_owner_mutation_claims m WHERE m.contact_point_id=v.contact_point_id),0)
      AND (SELECT COUNT(*) FROM person_contact_links l WHERE l.contact_point_id=v.contact_point_id AND l.ended_at IS NULL)=1
      AND NOT EXISTS (SELECT 1 FROM household_contact_links h WHERE h.campus_id=NEW.campus_id AND h.contact_point_id=v.contact_point_id AND h.ended_at IS NULL)
      AND p.active=1 AND p.deleted_at IS NULL AND p.identity_state='active' AND p.auth_disabled_at IS NULL AND r.loser_person_id IS NULL
  )) OR (NEW.expected_owner_person_id IS NULL AND EXISTS (
    SELECT 1 FROM verified_contact_owners v JOIN people p ON p.id=v.person_id
    JOIN campus_memberships cm ON cm.person_id=p.id AND cm.campus_id=NEW.campus_id AND cm.active=1
    LEFT JOIN person_merge_redirects r ON r.loser_person_id=p.id
    WHERE v.contact_point_id=NEW.expected_contact_point_id
      AND (SELECT COUNT(*) FROM person_contact_links l WHERE l.contact_point_id=v.contact_point_id AND l.ended_at IS NULL)=1
      AND NOT EXISTS (SELECT 1 FROM household_contact_links h WHERE h.campus_id=NEW.campus_id AND h.contact_point_id=v.contact_point_id AND h.ended_at IS NULL)
      AND p.active=1 AND p.deleted_at IS NULL AND p.identity_state='active' AND p.auth_disabled_at IS NULL AND r.loser_person_id IS NULL
  )) THEN RAISE EXCEPTION 'identity_claim_binding_invalid'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_claim_operation_insert_guard BEFORE INSERT ON identity_claim_operations FOR EACH ROW EXECUTE FUNCTION identity_claim_operation_insert_guard();

CREATE OR REPLACE FUNCTION identity_claim_operations_identity_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'identity_claim_operation_immutable'; END;
$$;
CREATE TRIGGER identity_claim_operations_identity_immutable BEFORE UPDATE OF campus_id,source_record_id,challenge_id,expected_source_version,expected_source_digest,expected_contact_point_id,expected_owner_person_id,expected_owner_generation,expires_at ON identity_claim_operations FOR EACH ROW EXECUTE FUNCTION identity_claim_operations_identity_immutable();

CREATE OR REPLACE FUNCTION identity_claim_operation_transition_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.state<>OLD.state AND NOT (OLD.state='pending' AND NEW.state IN ('review','completed','expired')) THEN RAISE EXCEPTION 'identity_claim_transition_invalid'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_claim_operation_transition_guard BEFORE UPDATE OF state ON identity_claim_operations FOR EACH ROW EXECUTE FUNCTION identity_claim_operation_transition_guard();

CREATE OR REPLACE FUNCTION identity_claim_operation_completion_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.state='pending' AND NEW.state='completed' AND NOT EXISTS (
    SELECT 1 FROM identity_source_attachment_receipts r JOIN identity_source_attachment_commits c ON c.receipt_id=r.receipt_id
    WHERE r.claim_operation_id=OLD.operation_id AND r.person_id=NEW.result_person_id
      AND r.proof_kind=NEW.result_proof_kind AND c.source_record_id=OLD.source_record_id AND c.person_id=NEW.result_person_id
  ) THEN RAISE EXCEPTION 'identity_claim_completion_invalid'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_claim_operation_completion_guard BEFORE UPDATE OF state ON identity_claim_operations FOR EACH ROW EXECUTE FUNCTION identity_claim_operation_completion_guard();

CREATE OR REPLACE FUNCTION identity_claim_operation_completed_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.state='completed' AND (
    NEW.operation_id IS DISTINCT FROM OLD.operation_id OR NEW.campus_id IS DISTINCT FROM OLD.campus_id
    OR NEW.source_record_id IS DISTINCT FROM OLD.source_record_id OR NEW.challenge_id IS DISTINCT FROM OLD.challenge_id
    OR NEW.expected_source_version IS DISTINCT FROM OLD.expected_source_version OR NEW.expected_source_digest IS DISTINCT FROM OLD.expected_source_digest
    OR NEW.expected_contact_point_id IS DISTINCT FROM OLD.expected_contact_point_id
    OR NEW.expected_owner_person_id IS DISTINCT FROM OLD.expected_owner_person_id OR NEW.expected_owner_generation IS DISTINCT FROM OLD.expected_owner_generation
    OR NEW.state IS DISTINCT FROM OLD.state OR NEW.result_person_id IS DISTINCT FROM OLD.result_person_id
    OR NEW.result_proof_kind IS DISTINCT FROM OLD.result_proof_kind OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
  ) THEN RAISE EXCEPTION 'identity_claim_operation_completed_immutable'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_claim_operation_completed_immutable BEFORE UPDATE ON identity_claim_operations FOR EACH ROW EXECUTE FUNCTION identity_claim_operation_completed_immutable();

CREATE OR REPLACE FUNCTION identity_claim_person_contact_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(NEW.contact_point_id);
  IF NEW.ended_at IS NULL AND EXISTS (
    SELECT 1 FROM identity_claim_operations op JOIN identity_challenges c ON c.id=op.challenge_id
    JOIN identity_source_records s ON s.id=op.source_record_id
    WHERE op.expected_contact_point_id=NEW.contact_point_id AND op.state='pending' AND op.expires_at>datetime('now')
      AND c.consumed_at IS NOT NULL AND c.superseded_at IS NULL AND c.ownership_consumed_at IS NULL
      AND s.state='unlinked' AND s.version=op.expected_source_version AND s.source_digest=op.expected_source_digest
  ) THEN RAISE EXCEPTION 'identity_claim_contact_mutation_conflict'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_claim_person_contact_insert_guard BEFORE INSERT ON person_contact_links FOR EACH ROW EXECUTE FUNCTION identity_claim_person_contact_insert_guard();

CREATE OR REPLACE FUNCTION identity_claim_person_contact_reactivation_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(NEW.contact_point_id);
  IF OLD.ended_at IS NOT NULL AND NEW.ended_at IS NULL AND EXISTS (
    SELECT 1 FROM identity_claim_operations op JOIN identity_challenges c ON c.id=op.challenge_id
    JOIN identity_source_records s ON s.id=op.source_record_id
    WHERE op.expected_contact_point_id=NEW.contact_point_id AND op.state='pending' AND op.expires_at>datetime('now')
      AND c.consumed_at IS NOT NULL AND c.superseded_at IS NULL AND c.ownership_consumed_at IS NULL
      AND s.state='unlinked' AND s.version=op.expected_source_version AND s.source_digest=op.expected_source_digest
  ) THEN RAISE EXCEPTION 'identity_claim_contact_mutation_conflict'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_claim_person_contact_reactivation_guard BEFORE UPDATE OF ended_at ON person_contact_links FOR EACH ROW EXECUTE FUNCTION identity_claim_person_contact_reactivation_guard();

CREATE OR REPLACE FUNCTION identity_claim_household_contact_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(NEW.contact_point_id);
  IF NEW.ended_at IS NULL AND EXISTS (
    SELECT 1 FROM identity_claim_operations op JOIN identity_challenges c ON c.id=op.challenge_id
    JOIN identity_source_records s ON s.id=op.source_record_id
    WHERE op.campus_id=NEW.campus_id AND op.expected_contact_point_id=NEW.contact_point_id
      AND op.state='pending' AND op.expires_at>datetime('now')
      AND c.consumed_at IS NOT NULL AND c.superseded_at IS NULL AND c.ownership_consumed_at IS NULL
      AND s.state='unlinked' AND s.version=op.expected_source_version AND s.source_digest=op.expected_source_digest
  ) THEN RAISE EXCEPTION 'identity_claim_contact_mutation_conflict'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_claim_household_contact_insert_guard BEFORE INSERT ON household_contact_links FOR EACH ROW EXECUTE FUNCTION identity_claim_household_contact_insert_guard();

CREATE OR REPLACE FUNCTION identity_claim_household_contact_reactivation_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(NEW.contact_point_id);
  IF OLD.ended_at IS NOT NULL AND NEW.ended_at IS NULL AND EXISTS (
    SELECT 1 FROM identity_claim_operations op JOIN identity_challenges c ON c.id=op.challenge_id
    JOIN identity_source_records s ON s.id=op.source_record_id
    WHERE op.campus_id=NEW.campus_id AND op.expected_contact_point_id=NEW.contact_point_id
      AND op.state='pending' AND op.expires_at>datetime('now')
      AND c.consumed_at IS NOT NULL AND c.superseded_at IS NULL AND c.ownership_consumed_at IS NULL
      AND s.state='unlinked' AND s.version=op.expected_source_version AND s.source_digest=op.expected_source_digest
  ) THEN RAISE EXCEPTION 'identity_claim_contact_mutation_conflict'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_claim_household_contact_reactivation_guard BEFORE UPDATE OF ended_at ON household_contact_links FOR EACH ROW EXECUTE FUNCTION identity_claim_household_contact_reactivation_guard();

CREATE OR REPLACE FUNCTION identity_source_attachment_receipt_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM 1 FROM identity_source_records WHERE id=NEW.source_record_id FOR UPDATE;
  PERFORM 1 FROM identity_observations WHERE id=(SELECT observation_id FROM identity_source_records WHERE id=NEW.source_record_id) FOR UPDATE;
  PERFORM pg_advisory_xact_lock(NEW.person_id);
  PERFORM 1 FROM people WHERE id=NEW.person_id FOR UPDATE;
  PERFORM 1 FROM campus_memberships WHERE person_id=NEW.person_id AND campus_id=NEW.campus_id FOR UPDATE;
  PERFORM pg_advisory_xact_lock(NEW.contact_point_id);
  IF NOT EXISTS (
    SELECT 1 FROM identity_source_records s JOIN identity_observations o ON o.id=s.observation_id
    JOIN people p ON p.id=NEW.person_id
    JOIN campus_memberships cm ON cm.person_id=p.id AND cm.campus_id=NEW.campus_id AND cm.active=1
    LEFT JOIN person_merge_redirects redirect ON redirect.loser_person_id=p.id
    WHERE s.id=NEW.source_record_id AND s.campus_id=NEW.campus_id AND s.state='unlinked'
      AND s.version=NEW.source_version AND s.source_digest=NEW.source_digest
      AND s.provisional_person_id IS NULL
      AND o.status='provisional' AND o.linked_person_id IS NULL
      AND p.active=1 AND p.deleted_at IS NULL AND p.identity_state='active' AND p.auth_disabled_at IS NULL AND redirect.loser_person_id IS NULL
  ) OR (NEW.proof_kind='signed_session' AND NOT EXISTS (
    SELECT 1 FROM identity_source_records s JOIN people p ON p.id=NEW.person_id
    WHERE s.id=NEW.source_record_id AND s.attachment_policy='signed_in_or_claim' AND p.session_epoch=NEW.session_epoch
  )) OR (NEW.proof_kind='claim_owner' AND NOT EXISTS (
    SELECT 1 FROM identity_claim_operations op JOIN identity_challenges c ON c.id=op.challenge_id
    JOIN verified_contact_owners v ON v.contact_point_id=op.expected_contact_point_id AND v.person_id=NEW.person_id
    WHERE op.operation_id=NEW.claim_operation_id AND op.campus_id=NEW.campus_id AND op.source_record_id=NEW.source_record_id
      AND NEW.contact_point_id=op.expected_contact_point_id
      AND op.state='pending' AND op.expected_source_version=NEW.source_version AND op.expected_source_digest=NEW.source_digest
      AND op.expires_at>datetime('now')
      AND op.expected_owner_person_id=NEW.person_id AND op.expected_owner_generation=NEW.owner_generation
      AND NEW.owner_generation=COALESCE((SELECT MAX(generation) FROM contact_owner_mutation_claims m WHERE m.contact_point_id=v.contact_point_id),0)
      AND c.id=NEW.challenge_id AND c.purpose='claim' AND c.contact_point_id=op.expected_contact_point_id
      AND c.consumed_at IS NOT NULL AND c.superseded_at IS NULL AND c.ownership_consumed_at IS NULL
      AND (SELECT COUNT(*) FROM person_contact_links l WHERE l.contact_point_id=v.contact_point_id AND l.ended_at IS NULL)=1
      AND NOT EXISTS (SELECT 1 FROM household_contact_links h WHERE h.campus_id=NEW.campus_id AND h.contact_point_id=v.contact_point_id AND h.ended_at IS NULL)
  )) OR (NEW.proof_kind='clean_signup' AND NOT EXISTS (
    SELECT 1 FROM identity_claim_operations op JOIN identity_challenges c ON c.id=op.challenge_id
    JOIN identity_account_operations signup ON signup.operation_id=NEW.signup_account_operation_id
    JOIN identity_challenges signup_challenge ON signup_challenge.id=signup.challenge_id
    JOIN identity_account_proof_uses proof ON proof.operation_id=signup.operation_id AND proof.challenge_id=signup.challenge_id
    JOIN verified_contact_owners v ON v.contact_point_id=op.expected_contact_point_id AND v.person_id=NEW.person_id
    WHERE op.operation_id=NEW.claim_operation_id AND op.campus_id=NEW.campus_id AND op.source_record_id=NEW.source_record_id
      AND NEW.contact_point_id=op.expected_contact_point_id
      AND op.state='pending' AND op.expected_owner_person_id IS NULL
      AND op.expires_at>datetime('now')
      AND op.expected_source_version=NEW.source_version AND op.expected_source_digest=NEW.source_digest
      AND c.id=NEW.challenge_id AND c.purpose='claim' AND c.contact_point_id=op.expected_contact_point_id
      AND c.consumed_at IS NOT NULL AND c.superseded_at IS NULL AND c.ownership_consumed_at IS NULL
      AND signup.campus_id=NEW.campus_id AND signup.kind='signup' AND signup.state='completed'
      AND signup.result_person_id=NEW.person_id AND signup.reserved_person_id=NEW.person_id
      AND signup_challenge.contact_point_id=op.expected_contact_point_id AND signup_challenge.consumed_at IS NOT NULL
      AND proof.proof_category='signup_create' AND proof.person_id=NEW.person_id
      AND (SELECT COUNT(*) FROM person_contact_links l WHERE l.contact_point_id=v.contact_point_id AND l.ended_at IS NULL)=1
      AND NOT EXISTS (SELECT 1 FROM household_contact_links h WHERE h.campus_id=NEW.campus_id AND h.contact_point_id=v.contact_point_id AND h.ended_at IS NULL)
  )) THEN RAISE EXCEPTION 'identity_source_attachment_proof_invalid'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_source_attachment_receipt_guard BEFORE INSERT ON identity_source_attachment_receipts FOR EACH ROW EXECUTE FUNCTION identity_source_attachment_receipt_guard();

CREATE OR REPLACE FUNCTION identity_source_records_attachment_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.linked_person_id IS NULL AND NEW.linked_person_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM identity_source_attachment_receipts r WHERE r.source_record_id=OLD.id
      AND r.source_version=OLD.version AND r.source_digest=OLD.source_digest AND r.person_id=NEW.linked_person_id
  ) THEN RAISE EXCEPTION 'identity_source_direct_attachment_forbidden'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_source_records_attachment_guard BEFORE UPDATE OF linked_person_id ON identity_source_records FOR EACH ROW EXECUTE FUNCTION identity_source_records_attachment_guard();

CREATE OR REPLACE FUNCTION identity_source_records_link_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.linked_person_id IS NOT NULL AND (
    NEW.linked_person_id IS DISTINCT FROM OLD.linked_person_id OR NEW.state IS DISTINCT FROM OLD.state
  ) THEN RAISE EXCEPTION 'identity_source_attachment_immutable'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_source_records_link_immutable BEFORE UPDATE OF linked_person_id,state ON identity_source_records FOR EACH ROW EXECUTE FUNCTION identity_source_records_link_immutable();

CREATE OR REPLACE FUNCTION identity_source_observation_attachment_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status='linked' AND EXISTS (SELECT 1 FROM identity_source_records x WHERE x.observation_id=OLD.id)
    AND NOT EXISTS (
      SELECT 1 FROM identity_source_records s JOIN identity_source_attachment_receipts r ON r.source_record_id=s.id
      WHERE s.observation_id=OLD.id AND s.state='linked' AND s.linked_person_id=NEW.linked_person_id
        AND r.person_id=NEW.linked_person_id AND r.source_version=s.version AND r.source_digest=s.source_digest
    ) THEN RAISE EXCEPTION 'identity_source_attachment_commit_invalid'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_source_observation_attachment_guard BEFORE UPDATE OF status,linked_person_id ON identity_observations FOR EACH ROW EXECUTE FUNCTION identity_source_observation_attachment_guard();

CREATE OR REPLACE FUNCTION identity_source_observation_link_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM identity_source_records s JOIN identity_source_attachment_receipts r ON r.source_record_id=s.id
    WHERE s.observation_id=OLD.id AND s.state='linked' AND s.linked_person_id=r.person_id
  ) AND NOT EXISTS (
    SELECT 1 FROM identity_source_records s WHERE s.observation_id=OLD.id AND s.state='linked'
      AND NEW.status='linked' AND NEW.linked_person_id IS NOT DISTINCT FROM s.linked_person_id
  ) THEN RAISE EXCEPTION 'identity_source_observation_immutable'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_source_observation_link_immutable BEFORE UPDATE OF status,linked_person_id ON identity_observations FOR EACH ROW EXECUTE FUNCTION identity_source_observation_link_immutable();

CREATE OR REPLACE FUNCTION identity_source_attachment_commit_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM identity_source_attachment_receipts r JOIN identity_source_records s ON s.id=r.source_record_id
    JOIN identity_observations o ON o.id=s.observation_id
    WHERE r.receipt_id=NEW.receipt_id AND r.campus_id=NEW.campus_id AND r.source_record_id=NEW.source_record_id
      AND r.person_id=NEW.person_id AND s.campus_id=NEW.campus_id AND s.state='linked' AND s.linked_person_id=NEW.person_id
      AND s.version=r.source_version AND s.source_digest=r.source_digest
      AND o.status='linked' AND o.linked_person_id=NEW.person_id
  ) THEN RAISE EXCEPTION 'identity_source_attachment_commit_invalid'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_source_attachment_commit_guard BEFORE INSERT ON identity_source_attachment_commits FOR EACH ROW EXECUTE FUNCTION identity_source_attachment_commit_guard();

CREATE OR REPLACE FUNCTION identity_source_provisional_operation_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM 1 FROM identity_source_records WHERE id=NEW.source_record_id FOR UPDATE;
  PERFORM pg_advisory_xact_lock(hashtextextended(lock_key,0)) FROM (
    SELECT 'email:'||o.normalized_email AS lock_key FROM identity_source_records s
      JOIN identity_observations o ON o.id=s.observation_id
      WHERE s.id=NEW.source_record_id AND o.normalized_email IS NOT NULL
    UNION ALL
    SELECT 'phone:'||o.normalized_phone AS lock_key FROM identity_source_records s
      JOIN identity_observations o ON o.id=s.observation_id
      WHERE s.id=NEW.source_record_id AND o.normalized_phone IS NOT NULL
  ) contact_locks ORDER BY lock_key;
  IF NOT EXISTS (
    SELECT 1 FROM identity_source_records s JOIN identity_observations o ON o.id=s.observation_id
    WHERE s.id=NEW.source_record_id AND s.campus_id=NEW.campus_id AND s.source IN ('group','newcomer','import')
      AND s.attachment_policy='observation_only' AND s.state='unlinked' AND s.linked_person_id IS NULL
      AND s.provisional_person_id IS NULL AND s.version=NEW.source_version AND s.source_digest=NEW.source_digest
      AND o.status='provisional' AND o.linked_person_id IS NULL
  ) OR EXISTS (SELECT 1 FROM people p WHERE p.id=NEW.reserved_person_id)
  THEN RAISE EXCEPTION 'identity_source_provisional_reservation_invalid'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_source_provisional_operation_insert_guard BEFORE INSERT ON identity_source_provisional_operations FOR EACH ROW EXECUTE FUNCTION identity_source_provisional_operation_insert_guard();

CREATE OR REPLACE FUNCTION identity_source_provisional_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF COALESCE(OLD.provisional_person_id,0)<>COALESCE(NEW.provisional_person_id,0) AND (
    OLD.provisional_person_id IS NOT NULL OR NEW.provisional_person_id IS NULL OR NEW.linked_person_id IS NOT NULL
    OR NEW.state<>'unlinked' OR NEW.source NOT IN ('group','newcomer','import') OR NEW.attachment_policy<>'observation_only'
    OR NOT EXISTS (SELECT 1 FROM identity_source_provisional_operations op WHERE op.source_record_id=NEW.id
      AND op.campus_id=NEW.campus_id AND op.source_version=NEW.version AND op.source_digest=NEW.source_digest
      AND op.reserved_person_id=NEW.provisional_person_id)
    OR NOT EXISTS (SELECT 1 FROM people p WHERE p.id=NEW.provisional_person_id AND p.active=0 AND p.deleted_at IS NULL
      AND p.identity_state='provisional' AND p.auth_disabled_at IS NOT NULL AND p.provisional_source=NEW.source)
    OR NOT EXISTS (SELECT 1 FROM person_contact_links l JOIN contact_points cp ON cp.id=l.contact_point_id
      JOIN identity_observations o ON o.id=NEW.observation_id WHERE l.person_id=NEW.provisional_person_id AND l.ended_at IS NULL
        AND l.notification_enabled=1 AND ((cp.kind='email' AND cp.normalized_value=o.normalized_email) OR (cp.kind='phone' AND cp.normalized_value=o.normalized_phone)))
    OR EXISTS (SELECT 1 FROM person_contact_links l JOIN verified_contact_owners v ON v.contact_point_id=l.contact_point_id
      WHERE l.person_id=NEW.provisional_person_id AND l.ended_at IS NULL)
    OR EXISTS (SELECT 1 FROM person_contact_links candidate JOIN person_contact_links existing
      ON existing.contact_point_id=candidate.contact_point_id
      WHERE candidate.person_id=NEW.provisional_person_id AND candidate.ended_at IS NULL
        AND existing.person_id<>NEW.provisional_person_id AND existing.ended_at IS NULL)
    OR EXISTS (SELECT 1 FROM person_contact_links candidate JOIN household_contact_links household
      ON household.contact_point_id=candidate.contact_point_id
      WHERE candidate.person_id=NEW.provisional_person_id AND candidate.ended_at IS NULL
        AND household.ended_at IS NULL)
  ) THEN RAISE EXCEPTION 'identity_source_provisional_invalid'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_source_provisional_guard BEFORE UPDATE OF provisional_person_id ON identity_source_records FOR EACH ROW EXECUTE FUNCTION identity_source_provisional_guard();

CREATE OR REPLACE FUNCTION identity_source_provisional_receipt_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM identity_source_provisional_operations op JOIN identity_source_records s ON s.id=op.source_record_id
    JOIN people p ON p.id=op.reserved_person_id
    WHERE op.operation_id=NEW.operation_id AND op.campus_id=NEW.campus_id AND op.source_record_id=NEW.source_record_id
      AND op.source_version=NEW.source_version AND op.source_digest=NEW.source_digest AND op.reserved_person_id=NEW.person_id
      AND s.campus_id=NEW.campus_id AND s.provisional_person_id=NEW.person_id AND s.state='unlinked'
      AND s.version=NEW.source_version AND s.source_digest=NEW.source_digest
      AND p.active=0 AND p.deleted_at IS NULL AND p.identity_state='provisional' AND p.auth_disabled_at IS NOT NULL
  ) THEN RAISE EXCEPTION 'identity_source_provisional_commit_invalid'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER identity_source_provisional_receipt_guard BEFORE INSERT ON identity_source_provisional_receipts FOR EACH ROW EXECUTE FUNCTION identity_source_provisional_receipt_guard();

CREATE OR REPLACE FUNCTION identity_source_provisional_operations_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'identity_source_provisional_operations_append_only'; END;
$$;
CREATE TRIGGER identity_source_provisional_operations_append_only_update BEFORE UPDATE ON identity_source_provisional_operations FOR EACH ROW EXECUTE FUNCTION identity_source_provisional_operations_append_only();
CREATE TRIGGER identity_source_provisional_operations_append_only_delete BEFORE DELETE ON identity_source_provisional_operations FOR EACH ROW EXECUTE FUNCTION identity_source_provisional_operations_append_only();

CREATE OR REPLACE FUNCTION identity_source_provisional_receipts_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'identity_source_provisional_receipts_append_only'; END;
$$;
CREATE TRIGGER identity_source_provisional_receipts_append_only_update BEFORE UPDATE ON identity_source_provisional_receipts FOR EACH ROW EXECUTE FUNCTION identity_source_provisional_receipts_append_only();
CREATE TRIGGER identity_source_provisional_receipts_append_only_delete BEFORE DELETE ON identity_source_provisional_receipts FOR EACH ROW EXECUTE FUNCTION identity_source_provisional_receipts_append_only();

CREATE OR REPLACE FUNCTION identity_source_attachment_receipts_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'identity_source_attachment_receipts_append_only'; END;
$$;
CREATE TRIGGER identity_source_attachment_receipts_append_only_update BEFORE UPDATE ON identity_source_attachment_receipts FOR EACH ROW EXECUTE FUNCTION identity_source_attachment_receipts_append_only();
CREATE TRIGGER identity_source_attachment_receipts_append_only_delete BEFORE DELETE ON identity_source_attachment_receipts FOR EACH ROW EXECUTE FUNCTION identity_source_attachment_receipts_append_only();

CREATE OR REPLACE FUNCTION identity_source_attachment_commits_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'identity_source_attachment_commits_append_only'; END;
$$;
CREATE TRIGGER identity_source_attachment_commits_append_only_update BEFORE UPDATE ON identity_source_attachment_commits FOR EACH ROW EXECUTE FUNCTION identity_source_attachment_commits_append_only();
CREATE TRIGGER identity_source_attachment_commits_append_only_delete BEFORE DELETE ON identity_source_attachment_commits FOR EACH ROW EXECUTE FUNCTION identity_source_attachment_commits_append_only();
