// e2e-pg setup: runs once per test file INSIDE the pool (like test/e2e/setup.ts),
// but against Postgres over the HYPERDRIVE binding instead of D1. e2e-pg does NOT
// get D1's per-test isolated-storage rollback, so this reseeds per FILE: TRUNCATE
// every table (RESTART IDENTITY CASCADE) then reload the same demo seed the D1
// path uses, so every file starts from the identical baseline. Files run serially
// (fileParallelism: false) because they share one database. The schema itself is
// created once in ./global-setup.ts (Node); here we only reset + reseed data.
import { env } from 'cloudflare:test';
import postgres from 'postgres';
import seedSql from '../../seed/dev-seed.sql?raw';

// Same comment-strip + ';'-split the D1 setup and seed-supabase.mjs use, so both
// backends load the identical statements.
function seedStatements(sql: string): string[] {
  return sql
    .split('\n')
    .filter((line) => !line.trimStart().startsWith('--'))
    .join('\n')
    .split(';')
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

const hyperdrive = (env as { HYPERDRIVE?: { connectionString: string } }).HYPERDRIVE;
if (!hyperdrive) throw new Error('e2e-pg setup: HYPERDRIVE binding missing');

// Request-scoped-style client, mirroring src/lib/dbProvider.ts (prepare:false +
// fetch_types:false for the Hyperdrive connection). int8 stays a string here — the
// setup only issues DDL/DML and reads table names, never COUNT results.
const sql = postgres(hyperdrive.connectionString, {
  max: 1,
  fetch_types: false,
  prepare: false,
  onnotice: () => {},
});
try {
  // Clear private rows before public rows because both private tables reference
  // public records. Keep the qualified order explicit so later private tables
  // cannot survive this per-file reset accidentally.
  await sql.unsafe(
    'TRUNCATE church_private.stripe_checkout_requests, church_private.stripe_webhook_events',
  );

  const tables = await sql.unsafe<{ tablename: string }[]>(
    "SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename <> '_migrations'",
  );
  if (tables.length > 0) {
    const list = tables.map((t) => `"${t.tablename}"`).join(', ');
    await sql.unsafe(`TRUNCATE ${list} RESTART IDENTITY CASCADE`);
  }

  for (const statement of seedStatements(seedSql)) {
    await sql.unsafe(statement);
  }

  // The seed inserts explicit ids, which never advances the identity sequences
  // (RESTART IDENTITY reset them to 1). Bump each `id` sequence past the seeded max
  // so a later autogenerated insert can't collide — the same fix seed-supabase.mjs
  // applies after seeding.
  const idTables = await sql.unsafe<{ table_name: string }[]>(
    "SELECT table_name FROM information_schema.columns WHERE column_name = 'id' AND is_identity = 'YES' AND table_schema = 'public'",
  );
  for (const { table_name } of idTables) {
    await sql.unsafe(
      `SELECT setval(pg_get_serial_sequence('${table_name}', 'id'), (SELECT coalesce(max(id), 1) FROM "${table_name}"))`,
    );
  }
} finally {
  await sql.end();
}
