import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { PgAdapter } from '../../src/lib/pgAdapter';
import { hasPg, pgClient, resetSchema } from './helpers';

describe.skipIf(!hasPg)('PgAdapter', () => {
  const sql = hasPg ? pgClient() : (null as never);
  let db: PgAdapter;
  beforeAll(async () => {
    await resetSchema(sql);
    await sql.unsafe(
      'CREATE TABLE t (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name text UNIQUE, n integer)',
    );
    db = new PgAdapter(sql);
  });
  afterAll(async () => { await sql?.end(); });

  it('run() inserts and reports meta.changes', async () => {
    const r = await db.prepare('INSERT INTO t (name, n) VALUES (?, ?)').bind('a', 1).run();
    expect(r.meta.changes).toBe(1);
  });
  it('first() returns row, column form, and null when empty', async () => {
    expect(await db.prepare('SELECT name FROM t WHERE name = ?').bind('a').first<{ name: string }>()).toEqual({ name: 'a' });
    expect(await db.prepare('SELECT name FROM t WHERE name = ?').bind('a').first('name')).toBe('a');
    expect(await db.prepare('SELECT name FROM t WHERE name = ?').bind('zz').first()).toBeNull();
  });
  it('all() returns results array', async () => {
    await db.prepare('INSERT INTO t (name, n) VALUES (?, ?)').bind('b', 2).run();
    const { results } = await db.prepare('SELECT name FROM t ORDER BY name').all<{ name: string }>();
    expect(results.map((r) => r.name)).toEqual(['a', 'b']);
  });
  it('INSERT ... RETURNING id works through first()', async () => {
    const row = await db.prepare('INSERT INTO t (name) VALUES (?) RETURNING id').bind('c').first<{ id: number }>();
    expect(typeof row?.id).toBe('number');
  });
  it('batch() is atomic — a failing statement rolls back the whole batch', async () => {
    await expect(
      db.batch([
        db.prepare('INSERT INTO t (name) VALUES (?)').bind('batch-ok'),
        db.prepare('INSERT INTO t (name) VALUES (?)').bind('a'), // UNIQUE violation
      ]),
    ).rejects.toThrow();
    expect(await db.prepare('SELECT 1 AS x FROM t WHERE name = ?').bind('batch-ok').first()).toBeNull();
  });
  it('batch() returns per-statement results in order', async () => {
    const [r1, r2] = await db.batch([
      db.prepare('INSERT INTO t (name) VALUES (?)').bind('b1'),
      db.prepare('SELECT count(*)::int AS c FROM t'),
    ]);
    expect(r1.meta.changes).toBe(1);
    expect((r2.results[0] as { c: number }).c).toBeGreaterThan(0);
  });
  it('unique violations surface postgres code 23505', async () => {
    const err = await db.prepare('INSERT INTO t (name) VALUES (?)').bind('a').run().catch((e) => e);
    expect((err as { code?: string }).code).toBe('23505');
  });
  it('rejects undefined bind values like D1 does', () => {
    // bind() rejects undefined synchronously (matching D1, which throws at bind
    // time), so assert on the throwing call itself rather than the run() promise.
    expect(() => db.prepare('SELECT ?').bind(undefined)).toThrow(/undefined/i);
  });
});
