import { copyFile, mkdir, open, readFile, rename, unlink } from 'node:fs/promises';
import { dirname } from 'node:path';

export const GENERATED_MARKER = '// Generated by Church4Christ setup; edit church.config.json and rerun setup.';

export function classifyConfig(content, knownBaseline) {
  if (content.startsWith(GENERATED_MARKER)) return 'generated';
  if (content === knownBaseline) return 'baseline';
  return 'unrecognized';
}

export async function writeAtomic(path, content, { allowReplace = false, backup = false } = {}) {
  await mkdir(dirname(path), { recursive: true });
  let existing = null;
  try {
    existing = await readFile(path, 'utf8');
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
  if (existing === content) return { changed: false, backupPath: null };
  if (existing !== null && !allowReplace) throw new Error(`Refusing to overwrite unrecognized file: ${path}`);

  let backupPath = null;
  if (existing !== null && backup) {
    backupPath = `${path}.bak-${new Date().toISOString().replace(/[:.]/g, '-')}`;
    await copyFile(path, backupPath);
  }

  const temporaryPath = `${path}.tmp-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  let handle;
  let ownsTemporaryPath = false;
  try {
    handle = await open(temporaryPath, 'wx', 0o600);
    ownsTemporaryPath = true;
    await handle.writeFile(content, 'utf8');
    await handle.close();
    handle = undefined;
    await rename(temporaryPath, path);
  } catch (error) {
    await handle?.close().catch(() => {});
    if (ownsTemporaryPath) await unlink(temporaryPath).catch(() => {});
    throw error;
  }
  return { changed: true, backupPath };
}
