import { constants } from 'node:fs';
import { copyFile, lstat, mkdir, open, readFile, rename, unlink } from 'node:fs/promises';
import { dirname } from 'node:path';

export const GENERATED_MARKER = '// Generated by Church4Christ setup; edit church.config.json and rerun setup.';

export function classifyConfig(content, knownBaseline) {
  if (content.startsWith(GENERATED_MARKER)) return 'generated';
  if (content === knownBaseline) return 'baseline';
  return 'unrecognized';
}

async function readSnapshot(path) {
  try {
    const stats = await lstat(path, { bigint: true });
    if (stats.isSymbolicLink()) throw new Error(`Refusing to replace symbolic link: ${path}`);
    return { content: await readFile(path, 'utf8'), dev: stats.dev, ino: stats.ino };
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}

async function assertUnchanged(path, approved) {
  const current = await readSnapshot(path);
  const changed = approved === null
    ? current !== null
    : current === null || current.dev !== approved.dev || current.ino !== approved.ino || current.content !== approved.content;
  if (changed) throw new Error(`Target changed after approval; refusing to overwrite: ${path}`);
}

async function createExclusiveBackup(path, timestamp) {
  const base = `${path}.bak-${timestamp}`;
  for (let attempt = 0; attempt < 1000; attempt += 1) {
    const candidate = attempt === 0 ? base : `${base}-${attempt}`;
    try {
      await copyFile(path, candidate, constants.COPYFILE_EXCL);
      return candidate;
    } catch (error) {
      if (error.code !== 'EEXIST') throw error;
    }
  }
  throw new Error(`Unable to create an exclusive backup for ${path}`);
}

/**
 * @param {string} path
 * @param {string} content
 * @param {{ allowReplace?: boolean, backup?: boolean, beforeReplace?: () => void | Promise<void> }} [options]
 */
export async function writeAtomic(path, content, options = {}) {
  const { allowReplace = false, backup = false, beforeReplace } = options;
  await mkdir(dirname(path), { recursive: true });
  const approved = await readSnapshot(path);
  if (approved?.content === content) return { changed: false, backupPath: null };
  if (approved !== null && !allowReplace) throw new Error(`Refusing to overwrite unrecognized file: ${path}`);

  let backupPath = null;
  if (approved !== null && backup) {
    await assertUnchanged(path, approved);
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    backupPath = await createExclusiveBackup(path, timestamp);
  }

  const temporaryPath = `${path}.tmp-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  let handle;
  let ownsTemporaryPath = false;
  try {
    handle = await open(temporaryPath, 'wx', 0o600);
    ownsTemporaryPath = true;
    await handle.writeFile(content, 'utf8');
    await handle.sync();
    await handle.close();
    handle = undefined;
    if (beforeReplace) await beforeReplace();
    await assertUnchanged(path, approved);
    await rename(temporaryPath, path);
    ownsTemporaryPath = false;
    const directory = await open(dirname(path), 'r');
    try {
      await directory.sync();
    } finally {
      await directory.close();
    }
  } catch (error) {
    await handle?.close().catch(() => {});
    if (ownsTemporaryPath) await unlink(temporaryPath).catch(() => {});
    throw error;
  }
  return { changed: true, backupPath };
}
