import { constants } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { copyFile, link, lstat, mkdir, open, readFile, readdir, rename, rmdir, unlink } from 'node:fs/promises';
import { dirname } from 'node:path';

export const GENERATED_MARKER = '// Generated by Church4Christ setup; edit church.config.json and rerun setup.';

export function classifyConfig(content, knownBaseline) {
  if (content.startsWith(GENERATED_MARKER)) return 'generated';
  if (content === knownBaseline) return 'baseline';
  return 'unrecognized';
}

async function readSnapshot(path) {
  try {
    const stats = await lstat(path, { bigint: true });
    if (stats.isSymbolicLink()) throw new Error(`Refusing to replace symbolic link: ${path}`);
    return { content: await readFile(path, 'utf8'), dev: stats.dev, ino: stats.ino };
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}

async function assertUnchanged(path, approved) {
  const current = await readSnapshot(path);
  const changed = approved === null
    ? current !== null
    : current === null || current.dev !== approved.dev || current.ino !== approved.ino || current.content !== approved.content;
  if (changed) throw new Error(`Target changed after approval; refusing to overwrite: ${path}`);
}

async function createExclusiveBackup(path, timestamp) {
  const base = `${path}.bak-${timestamp}`;
  for (let attempt = 0; attempt < 1000; attempt += 1) {
    const candidate = attempt === 0 ? base : `${base}-${attempt}`;
    try {
      await copyFile(path, candidate, constants.COPYFILE_EXCL);
      return candidate;
    } catch (error) {
      if (error.code !== 'EEXIST') throw error;
    }
  }
  throw new Error(`Unable to create an exclusive backup for ${path}`);
}

const STALE_LOCK_MS = 5 * 60 * 1000;
const RANDOM_UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
// Node/platform combinations use these codes when directory fsync is unsupported.
const UNSUPPORTED_DIRECTORY_SYNC = new Set(['EINVAL', 'ENOTSUP', 'EOPNOTSUPP']);

function sameSnapshot(left, right) {
  return left !== null && right !== null &&
    left.dev === right.dev && left.ino === right.ino && left.content === right.content;
}

async function removeVerified(path, approved) {
  const current = await readSnapshot(path);
  if (!sameSnapshot(current, approved)) {
    throw new Error(`Lock identity changed; refusing to remove it: ${path}`);
  }
  await unlink(path);
}

async function removeOwnedIdentity(path, identity) {
  try {
    const current = await lstat(path, { bigint: true });
    if (current.dev === identity.dev && current.ino === identity.ino) await unlink(path);
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
}

function parseLockOwner(snapshot, now) {
  let owner;
  try {
    owner = JSON.parse(snapshot.content);
  } catch {
    throw new Error('Cannot safely reclaim malformed configuration lock');
  }
  if (
    !owner ||
    owner.version !== 1 ||
    !Number.isSafeInteger(owner.pid) ||
    owner.pid <= 0 ||
    !Number.isFinite(owner.createdAt) ||
    typeof owner.token !== 'string' ||
    !RANDOM_UUID.test(owner.token)
  ) {
    throw new Error('Cannot safely reclaim malformed configuration lock');
  }
  return { ...owner, staleByAge: now - owner.createdAt >= STALE_LOCK_MS };
}

function processState(pid) {
  try {
    process.kill(pid, 0);
    return 'active';
  } catch (error) {
    if (error.code === 'ESRCH') return 'dead';
    if (error.code === 'EPERM') return 'active';
    return 'unknown';
  }
}

async function acquireReclaimGuard(path, record, stateForProcess) {
  for (let attempt = 0; attempt < 3; attempt += 1) {
    let handle;
    let identity;
    try {
      handle = await open(path, 'wx', 0o600);
      identity = await handle.stat({ bigint: true });
      await handle.writeFile(record, 'utf8');
      await handle.sync();
      await handle.close();
      handle = undefined;
      const approved = await readSnapshot(path);
      return async () => {
        const current = await readSnapshot(path);
        if (sameSnapshot(current, approved)) await removeVerified(path, current);
      };
    } catch (error) {
      await handle?.close().catch(() => {});
      if (identity) await removeOwnedIdentity(path, identity);
      if (error.code !== 'EEXIST') throw error;
    }

    const approved = await readSnapshot(path);
    if (!approved) continue;
    const owner = parseLockOwner(approved, Date.now());
    const state = stateForProcess(owner.pid);
    if (!owner.staleByAge || state === 'active') {
      throw new Error('Configuration write already in progress; stale-lock reclamation is active');
    }
    if (state !== 'dead') {
      throw new Error('Configuration reclamation owner is unknown and cannot safely be reclaimed');
    }
    await removeVerified(path, approved);
  }
  throw new Error('Configuration write already in progress; stale-lock reclamation is active');
}

async function cleanupStaleOrphanTickets(lockDirectory, currentToken, stateForProcess) {
  const entries = await readdir(lockDirectory, { withFileTypes: true });
  for (const entry of entries) {
    const match = /^ticket-([0-9a-f-]+)$/.exec(entry.name);
    if (!entry.isFile() || !match || match[1] === currentToken || !RANDOM_UUID.test(match[1])) continue;
    const ticketPath = `${lockDirectory}/${entry.name}`;
    let approved;
    try {
      approved = await readSnapshot(ticketPath);
    } catch (error) {
      if (/symbolic link/i.test(error.message)) continue;
      throw error;
    }
    if (!approved) continue;
    let owner;
    try {
      owner = parseLockOwner(approved, Date.now());
    } catch {
      continue;
    }
    if (owner.token !== match[1] || !owner.staleByAge || stateForProcess(owner.pid) !== 'dead') continue;
    await removeVerified(ticketPath, approved);
  }
}

async function acquireSetupLock(path, stateForProcess) {
  const lockDirectory = `${path}.setup-lock`;
  try {
    await mkdir(lockDirectory, { recursive: true });
  } catch (error) {
    if (error.code !== 'EEXIST') throw error;
  }
  const lockStats = await lstat(lockDirectory);
  if (lockStats.isSymbolicLink() || !lockStats.isDirectory()) {
    throw new Error(`Refusing symbolic or non-directory configuration lock: ${lockDirectory}`);
  }
  const token = randomUUID();
  const createdAt = Date.now();
  const ticketPath = `${lockDirectory}/ticket-${token}`;
  const ownerPath = `${lockDirectory}/owner`;
  const reclaimPath = `${lockDirectory}/reclaim`;
  const record = `${JSON.stringify({ version: 1, pid: process.pid, createdAt, token })}\n`;
  let ticket;
  let ticketIdentity;
  try {
    ticket = await open(ticketPath, 'wx', 0o600);
    ticketIdentity = await ticket.stat({ bigint: true });
    await ticket.writeFile(record, 'utf8');
    await ticket.sync();
    await ticket.close();
    ticket = undefined;
  } catch (error) {
    await ticket?.close().catch(() => {});
    if (ticketIdentity) await removeOwnedIdentity(ticketPath, ticketIdentity);
    await rmdir(lockDirectory).catch(() => {});
    throw error;
  }
  const ticketSnapshot = await readSnapshot(ticketPath);

  const releaseTicket = async () => {
    const currentOwner = await readSnapshot(ownerPath);
    if (sameSnapshot(currentOwner, ticketSnapshot)) await removeVerified(ownerPath, currentOwner);
    const currentTicket = await readSnapshot(ticketPath);
    if (sameSnapshot(currentTicket, ticketSnapshot)) await removeVerified(ticketPath, currentTicket);
    await rmdir(lockDirectory).catch((error) => {
      if (!['ENOENT', 'ENOTEMPTY', 'EEXIST'].includes(error.code)) throw error;
    });
  };

  try {
    for (let attempt = 0; attempt < 3; attempt += 1) {
      try {
        await link(ticketPath, ownerPath);
        await cleanupStaleOrphanTickets(lockDirectory, token, stateForProcess);
        return releaseTicket;
      } catch (error) {
        if (error.code !== 'EEXIST') throw error;
      }

      const approvedOwner = await readSnapshot(ownerPath);
      if (!approvedOwner) continue;
      const owner = parseLockOwner(approvedOwner, Date.now());
      const state = stateForProcess(owner.pid);
      if (!owner.staleByAge || state === 'active') {
        throw new Error('Configuration write already in progress; refusing concurrent setup write');
      }
      if (state !== 'dead') {
        throw new Error('Configuration lock owner is unknown and cannot safely be reclaimed');
      }

      const matchingTicketPath = `${lockDirectory}/ticket-${owner.token}`;
      const approvedMatchingTicket = await readSnapshot(matchingTicketPath);
      if (approvedMatchingTicket && !sameSnapshot(approvedMatchingTicket, approvedOwner)) {
        throw new Error('Configuration owner ticket identity does not match; cannot safely reclaim lock');
      }
      const releaseReclaim = await acquireReclaimGuard(reclaimPath, record, stateForProcess);
      try {
        const currentOwner = await readSnapshot(ownerPath);
        if (!sameSnapshot(currentOwner, approvedOwner)) continue;
        const currentMatchingTicket = await readSnapshot(matchingTicketPath);
        const ticketChanged = approvedMatchingTicket === null
          ? currentMatchingTicket !== null
          : !sameSnapshot(currentMatchingTicket, approvedMatchingTicket);
        if (ticketChanged) {
          throw new Error('Configuration owner ticket changed; cannot safely reclaim lock');
        }
        await removeVerified(ownerPath, approvedOwner);
        if (approvedMatchingTicket) await removeVerified(matchingTicketPath, approvedMatchingTicket);
      } finally {
        await releaseReclaim();
      }
    }
    throw new Error('Configuration write already in progress; refusing concurrent setup write');
  } catch (error) {
    await releaseTicket();
    throw error;
  }
}

/**
 * Flushes the containing directory after rename. Some platforms explicitly report
 * directory fsync as unsupported; only those codes are ignored.
 * @param {string} path
 * @param {(path: string, flags: string) => Promise<{ sync: () => Promise<void>, close: () => Promise<void> }>} [openDirectory]
 * @internal The second argument exists only for deterministic filesystem tests.
 */
export async function _syncParentDirectory(path, openDirectory = open) {
  let directory;
  try {
    directory = await openDirectory(dirname(path), 'r');
    await directory.sync();
  } catch (error) {
    if (!UNSUPPORTED_DIRECTORY_SYNC.has(error.code)) throw error;
  } finally {
    await directory?.close();
  }
}

/**
 * @param {string} path
 * @param {string} content
 * @param {{ allowReplace?: boolean, backup?: boolean, beforeReplace?: () => void | Promise<void>, _processState?: (pid: number) => 'active' | 'dead' | 'unknown' }} [options]
 * @internal `_processState` is a narrow deterministic lock-recovery test hook.
 */
export async function writeAtomic(path, content, options = {}) {
  const { allowReplace = false, backup = false, beforeReplace, _processState = processState } = options;
  await mkdir(dirname(path), { recursive: true });
  const releaseLock = await acquireSetupLock(path, _processState);
  try {
    const approved = await readSnapshot(path);
    if (approved?.content === content) return { changed: false, backupPath: null };
    if (approved !== null && !allowReplace) throw new Error(`Refusing to overwrite unrecognized file: ${path}`);

    let backupPath = null;
    if (approved !== null && backup) {
      await assertUnchanged(path, approved);
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      backupPath = await createExclusiveBackup(path, timestamp);
    }

    const temporaryPath = `${path}.tmp-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
    let handle;
    let ownsTemporaryPath = false;
    try {
      handle = await open(temporaryPath, 'wx', 0o600);
      ownsTemporaryPath = true;
      await handle.writeFile(content, 'utf8');
      await handle.sync();
      await handle.close();
      handle = undefined;
      if (beforeReplace) await beforeReplace();
      await assertUnchanged(path, approved);
      await rename(temporaryPath, path);
      ownsTemporaryPath = false;
      await _syncParentDirectory(path);
    } catch (error) {
      await handle?.close().catch(() => {});
      if (ownsTemporaryPath) await unlink(temporaryPath).catch(() => {});
      throw error;
    }
    return { changed: true, backupPath };
  } finally {
    await releaseLock();
  }
}
