import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const d1 = readFileSync('migrations/0037_planning_center.sql', 'utf8');
const pg = readFileSync('migrations-supabase/0037_planning_center.sql', 'utf8');
const webhookRoute = readFileSync('src/pages/api/planning-center/webhook/[connectionId].ts', 'utf8');
const connectionRoute = readFileSync('src/pages/api/planning-center/connection.ts', 'utf8');

describe('Planning Center 0037 schema contract', () => {
  it('ships paired connection, cursor, lease, receipt, mapping, webhook, and evidence tables', () => {
    for (const sql of [d1, pg]) {
      for (const name of [
        'planning_center_connections', 'planning_center_sync_cursors', 'planning_center_sync_jobs',
        'planning_center_sync_receipts', 'planning_center_person_mappings',
        'planning_center_webhook_receipts', 'planning_center_external_evidence',
        'planning_center_merge_mapping_snapshots', 'planning_center_merge_mapping_snapshot_seals',
      ]) expect(sql).toMatch(new RegExp(`CREATE TABLE ${name}`, 'i'));
      expect(sql).not.toMatch(/client_id|raw_pat|pat_ciphertext|secret_ciphertext|webhook_secret_ciphertext|provider_json|email|phone|normalized_name/i);
      expect(sql).toMatch(/append_only/i);
      expect(sql).toMatch(/lease/i);
      expect(sql).toMatch(/planning_center_person_mapping_identity_immutable/i);
      expect(sql).toMatch(/not_before/i);
      expect(sql).toMatch(/provider_person_remove_id/i);
      expect(sql).toMatch(/received_at/i);
    }
    expect(d1).toMatch(/CREATE INDEX idx_planning_center_sync_jobs_lease/i);
    expect(pg).toMatch(/CREATE INDEX idx_planning_center_sync_jobs_lease/i);
  });

  it('keeps application ids and timestamps portable across D1 and PostgreSQL', () => {
    expect(pg).toMatch(/id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/i);
    expect(pg).toMatch(/campus_id INTEGER NOT NULL REFERENCES public\.campuses\(id\)/i);
    expect(pg).not.toMatch(/\bBIGINT\b|\bTIMESTAMPTZ\b/i);
    expect(pg).toMatch(/last_success_at TEXT/i);
    expect(pg).toMatch(/created_at TEXT NOT NULL DEFAULT \(datetime\('now'\)\)/i);
  });

  it('keeps disabled connection history while allowing one current connection per campus', () => {
    for (const sql of [d1, pg]) {
      expect(sql).not.toMatch(/campus_id\s+(?:INTEGER|BIGINT)\s+NOT NULL UNIQUE/i);
      expect(sql).toMatch(/CREATE UNIQUE INDEX idx_planning_center_connections_current_campus[\s\S]*WHERE state IN \('active','paused','error'\)/i);
      expect(sql).toMatch(/CREATE UNIQUE INDEX idx_planning_center_connections_current_organization[\s\S]*WHERE state IN \('active','paused','error'\)/i);
      expect(sql).toMatch(/organization_id[\s\S]{0,180}(?:NOT GLOB '\*\[\^0-9\]\*'|~ '\^\[0-9\]\{1,32\}\$')/i);
    }
  });

  it('scopes webhook delivery replay protection to the connection generation', () => {
    for (const sql of [d1, pg]) {
      expect(sql).not.toMatch(/delivery_id\s+TEXT\s+NOT NULL\s+UNIQUE/i);
      expect(sql).toMatch(/UNIQUE\s*\(connection_id,\s*delivery_id\)/i);
    }
  });

  it('never uses backend-specific SQL randomness for durable webhook job ids', () => {
    expect(webhookRoute).not.toMatch(/\brandom\s*\(/i);
  });

  it('pins an organization to an active connection and requires an explicit disable before replacement', () => {
    expect(connectionRoute).toContain('organization_change_requires_disable');
    expect(connectionRoute).toContain('organization_already_connected');
    expect(connectionRoute).toContain("action === 'disable'");
    expect(connectionRoute).not.toMatch(/ON CONFLICT\(campus_id\) DO UPDATE/i);
  });

  it('namespaces provider identities and freezes exact mapping sets across merge approval and execution', () => {
    for (const sql of [d1, pg]) {
      expect(sql).not.toMatch(/source_record_id\s+(?:INTEGER|BIGINT)\s+NOT NULL\s+UNIQUE/i);
      expect(sql).toMatch(/planning_center_merge_mapping_snapshots/i);
      expect(sql).toMatch(/planning_center_merge_mapping_stale_guard/i);
      expect(sql).toMatch(/planning_center_merge_external_identity_review_guard/i);
      expect(sql).toMatch(/planning_center_merge_external_identity_decision_guard/i);
      expect(sql).toMatch(/planning_center_mapping_executing_(?:insert|update|delete)_guard/i);
      expect(sql).toMatch(/planning_center_merge_mapping_snapshots_append_only/i);
      expect(sql).toMatch(/planning_center_merge_mapping_snapshot_seals/i);
      expect(sql).toMatch(/planning_center_merge_mapping_snapshots_sealed/i);
    }
  });
});
