import ts from 'typescript';
import { renderWrangler } from '../render-wrangler.mjs';
import { result } from '../readiness.mjs';
import { parseJsoncObject } from '../jsonc.mjs';

const GENERATED_MARKER = '// Generated by Church4Christ setup; edit church.config.json and rerun setup.';
const EXPECTED_CRONS = Object.freeze(['0 13 * * *', '0 14 * * 4', '0 9 * * *']);
const DEPRECATED = 'WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE';

function workerCrons(source) {
  const file = ts.createSourceFile('worker.ts', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  if (file.parseDiagnostics.length) throw new Error('worker source could not be parsed');
  const constants = new Map();
  for (const statement of file.statements) {
    if (!ts.isVariableStatement(statement)) continue;
    for (const declaration of statement.declarationList.declarations) {
      if (ts.isIdentifier(declaration.name) && ts.isStringLiteral(declaration.initializer)) {
        constants.set(declaration.name.text, declaration.initializer.text);
      }
    }
  }
  const unwrap = (node) => {
    while (ts.isSatisfiesExpression(node) || ts.isParenthesizedExpression(node) || ts.isAsExpression(node) ||
        ts.isTypeAssertionExpression(node) || ts.isNonNullExpression(node)) node = node.expression;
    return node;
  };
  const exports = file.statements.filter((statement) => ts.isExportAssignment(statement) && !statement.isExportEquals);
  if (exports.length !== 1) throw new Error('worker must have exactly one default export');
  const handler = unwrap(exports[0].expression);
  if (!ts.isObjectLiteralExpression(handler)) throw new Error('default Worker handler must be an object literal');
  const scheduled = handler.properties.filter((property) => ts.isMethodDeclaration(property) &&
    ((ts.isIdentifier(property.name) || ts.isStringLiteral(property.name)) && property.name.text === 'scheduled'));
  if (scheduled.length !== 1 || scheduled[0].parameters.length < 1 || !ts.isIdentifier(scheduled[0].parameters[0].name) || !scheduled[0].body) {
    throw new Error('Worker handler must have one scheduled method with a controller parameter');
  }
  const controller = scheduled[0].parameters[0].name.text;
  const switches = [];
  const visit = (node) => {
    if (ts.isSwitchStatement(node)) {
      const expression = unwrap(node.expression);
      if (ts.isPropertyAccessExpression(expression) && expression.name.text === 'cron' &&
          ts.isIdentifier(unwrap(expression.expression)) && unwrap(expression.expression).text === controller) switches.push(node);
    }
    ts.forEachChild(node, visit);
  };
  visit(scheduled[0].body);
  if (switches.length !== 1) throw new Error('scheduled method must have exactly one controller.cron switch');
  const found = [];
  for (const clause of switches[0].caseBlock.clauses) {
    if (!ts.isCaseClause(clause)) continue;
    const expression = unwrap(clause.expression);
    if (ts.isStringLiteral(expression)) found.push(expression.text);
    else if (ts.isIdentifier(expression) && constants.has(expression.text)) found.push(constants.get(expression.text));
    else throw new Error('scheduled cron case is not a static string constant');
  }
  return found;
}

const same = (left, right) => left.length === right.length && left.every((value, index) => value === right[index]);

export async function checkConfig(options) {
  if (!options || !options.manifest || typeof options.manifest !== 'object') throw new TypeError('config check manifest is required');
  for (const key of ['template', 'config', 'workerSource']) {
    if (typeof options[key] !== 'string') throw new TypeError(`config check ${key} must be a string`);
  }
  if (options.hostEnv !== undefined && (!options.hostEnv || typeof options.hostEnv !== 'object' || Array.isArray(options.hostEnv))) {
    throw new TypeError('config check hostEnv must be an object');
  }
  let additionalFiles = [];
  if (options.files !== undefined) {
    if (Array.isArray(options.files)) {
      if (options.files.some((content) => typeof content !== 'string')) throw new TypeError('config check files must contain only strings');
      additionalFiles = [...options.files];
    } else {
      const plain = options.files && typeof options.files === 'object' &&
        (Object.getPrototypeOf(options.files) === Object.prototype || Object.getPrototypeOf(options.files) === null);
      if (!plain || Object.values(options.files).some((content) => typeof content !== 'string')) {
        throw new TypeError('config check files must be a plain string record or string array');
      }
      additionalFiles = Object.values(options.files);
    }
  }
  let parsed;
  try { parsed = parseJsoncObject(options.config, 'generated Wrangler configuration'); } catch {
    return [result('config.invalid', 'error', 'The generated Wrangler configuration is invalid JSONC.', 'Rerun setup to regenerate wrangler.jsonc.')];
  }
  const checks = [];
  if (!options.config.startsWith(GENERATED_MARKER)) {
    checks.push(result('config.generated-marker', 'error', 'wrangler.jsonc is not recognized as setup-generated.', 'Preserve custom changes, then rerun setup with explicit replacement approval.'));
  }
  if (/@@[A-Z_]+@@|\bYOUR_[A-Z0-9_]*\b/.test(options.config)) {
    checks.push(result('config.placeholder', 'error', 'wrangler.jsonc contains unresolved setup placeholders.', 'Rerun setup after providing all resource identifiers.'));
  }
  if (parsed.vars?.DB_BACKEND !== options.manifest.database || !['d1', 'supabase'].includes(parsed.vars?.DB_BACKEND)) {
    checks.push(result('config.backend', 'error', 'DB_BACKEND does not match the installation manifest.', 'Rerun setup to regenerate the provider configuration.'));
  }
  const bindingOk = options.manifest.database === 'd1'
    ? Array.isArray(parsed.d1_databases) && parsed.d1_databases.length === 1 && parsed.d1_databases[0]?.binding === 'DB' && !Object.hasOwn(parsed, 'hyperdrive')
    : Array.isArray(parsed.hyperdrive) && parsed.hyperdrive.length === 1 && parsed.hyperdrive[0]?.binding === 'HYPERDRIVE' && !Object.hasOwn(parsed, 'd1_databases');
  if (!bindingOk) {
    checks.push(result('config.binding', 'error', 'The configured database binding does not match the selected provider.', 'Rerun setup to restore the DB or HYPERDRIVE binding.'));
  }
  let desired;
  try { desired = renderWrangler(options.template, options.manifest); } catch {
    return [result('config.render', 'error', 'The desired Wrangler configuration cannot be rendered.', 'Repair the manifest and setup template before rerunning doctor.')];
  }
  if (options.config !== desired) {
    checks.push(result('config.drift', 'error', 'wrangler.jsonc differs from the canonical generated configuration.', 'Review local changes and rerun setup to regenerate the file.'));
  }
  let configuredCrons = parsed.triggers?.crons;
  let sourceCrons;
  try { sourceCrons = workerCrons(options.workerSource); } catch { sourceCrons = null; }
  if (!Array.isArray(configuredCrons) || configuredCrons.some((value) => typeof value !== 'string') ||
      !same(configuredCrons, EXPECTED_CRONS) || !sourceCrons || !same(sourceCrons, EXPECTED_CRONS)) {
    checks.push(result('config.worker-crons', 'error', 'Scheduled Worker branches and configured cron triggers do not match the canonical three schedules.', 'Restore the canonical reminder, digest, and backup cron strings.'));
  }
  if (options.config.includes(DEPRECATED) || additionalFiles.some((content) => content.includes(DEPRECATED)) ||
      Object.hasOwn(options.hostEnv ?? {}, DEPRECATED)) {
    checks.push(result('config.hyperdrive-env-deprecated', 'warning', `${DEPRECATED} is deprecated.`, 'Use CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE on the host instead.'));
  }
  return checks.length ? checks : [result('config.ok', 'info', 'The generated Wrangler configuration matches the manifest and Worker schedules.', 'No action is required.')];
}

export { workerCrons as extractScheduledCrons };
