#!/usr/bin/env node
/**
 * Design token build: design/foundation.json + design/themes/*.json
 *   -> src/styles/tokens.generated.css (gitignored)
 *
 * Gates every theme/mode on WCAG contrast (>= 4.5:1) before writing.
 * Plain Node ESM, zero dependencies. generateCss + contrastViolations are
 * exported as pure functions for tests.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

/** (foreground | background) semantic-key pairs gated at ratio >= 4.5. */
const CONTRAST_PAIRS = [
  ['ink', 'surface'],
  ['ink', 'surface-raised'],
  ['ink-muted', 'surface'],
  ['on-primary', 'primary'],
  ['on-accent', 'accent'],
  ['on-primary-soft', 'primary-soft'],
  ['on-accent-soft', 'accent-soft'],
  ['on-success', 'success'],
  ['on-warn', 'warn'],
  ['on-danger', 'danger'],
  ['on-info', 'info'],
  ['header-ink', 'header-bg'],
  ['footer-ink', 'footer-bg'],
];

const MIN_RATIO = 4.5;

/** Parse #RGB/#RGBA/#RRGGBB/#RRGGBBAA or rgb()/rgba() into {r,g,b} (0-255).
 * Alpha is ignored: gated pairs are opaque; rgba() only appears in scrim/shadows. */
function parseColor(value) {
  const v = String(value).trim();
  const hex = /^#([0-9a-fA-F]{3,8})$/.exec(v)?.[1];
  if (hex && (hex.length === 3 || hex.length === 4)) {
    return {
      r: parseInt(hex[0] + hex[0], 16),
      g: parseInt(hex[1] + hex[1], 16),
      b: parseInt(hex[2] + hex[2], 16),
    };
  }
  if (hex && (hex.length === 6 || hex.length === 8)) {
    return {
      r: parseInt(hex.slice(0, 2), 16),
      g: parseInt(hex.slice(2, 4), 16),
      b: parseInt(hex.slice(4, 6), 16),
    };
  }
  const rgb = /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*[\d.]+\s*)?\)$/.exec(v);
  if (rgb) return { r: Number(rgb[1]), g: Number(rgb[2]), b: Number(rgb[3]) };
  return null;
}

/** WCAG 2.x relative luminance. */
function luminance({ r, g, b }) {
  const [R, G, B] = [r, g, b].map((c) => {
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * R + 0.7152 * G + 0.0722 * B;
}

function contrastRatio(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

/**
 * Check every theme, every mode, every gated pair.
 * @returns {{theme: string, mode: string, pair: string, ratio: number}[]}
 */
export function contrastViolations(themes) {
  const violations = [];
  for (const theme of themes) {
    for (const [mode, colors] of Object.entries(theme.modes)) {
      for (const [fg, bg] of CONTRAST_PAIRS) {
        const fgc = colors[fg] != null ? parseColor(colors[fg]) : null;
        const bgc = colors[bg] != null ? parseColor(colors[bg]) : null;
        if (!fgc || !bgc) continue;
        const ratio = contrastRatio(fgc, bgc);
        if (ratio < MIN_RATIO) {
          violations.push({
            theme: theme.name,
            mode,
            pair: `${fg}|${bg}`,
            ratio: Math.round(ratio * 100) / 100,
          });
        }
      }
    }
  }
  return violations;
}

/** 'Fraunces Variable' + fallback -> quoted, joined CSS font stack. */
function fontStack({ family, fallback }) {
  const quoted = family.includes(' ') ? `'${family}'` : family;
  return `${quoted}, ${fallback}`;
}

function decls(entries) {
  return entries.map(([prop, value]) => `  ${prop}: ${value};`);
}

function colorDecls(colors) {
  return decls(Object.entries(colors).map(([k, v]) => [`--color-${k}`, v]));
}

/** Pure CSS generator. `themes` is an array of parsed theme JSON objects. */
export function generateCss(foundation, themes) {
  const out = [
    '/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit.',
    ' * Source of truth: design/foundation.json + design/themes/*.json */',
    '',
    ':root {',
    ...decls(Object.entries(foundation.type.scale).map(([k, v]) => [`--text-${k}`, v])),
    ...decls(Object.entries(foundation.type.leading).map(([k, v]) => [`--leading-${k}`, v])),
    ...decls(Object.entries(foundation.type.tracking).map(([k, v]) => [`--tracking-${k}`, v])),
    ...decls(Object.entries(foundation.container).map(([k, v]) => [`--container-${k}`, v])),
    ...decls(Object.entries(foundation.z).map(([k, v]) => [`--z-${k}`, v])),
    ...decls(Object.entries(foundation.motion).map(([k, v]) => [`--${k}`, v])),
    '}',
  ];

  for (const theme of themes) {
    const defaultMode = theme.defaultMode;
    const otherMode = defaultMode === 'light' ? 'dark' : 'light';
    out.push(
      '',
      `:root[data-theme="${theme.name}"] {`,
      ...decls(Object.entries(theme.fonts).map(([k, v]) => [`--font-${k}`, fontStack(v)])),
      ...decls(Object.entries(theme.radius).map(([k, v]) => [`--radius-${k}`, v])),
      ...decls(Object.entries(theme.shadow).map(([k, v]) => [`--shadow-${k}`, v])),
      ...colorDecls(theme.modes[defaultMode]),
      '}',
      '',
      `:root[data-theme="${theme.name}"][data-mode="${otherMode}"] {`,
      ...colorDecls(theme.modes[otherMode]),
      '}',
    );
  }

  return out.join('\n') + '\n';
}

function main() {
  const root = fileURLToPath(new URL('..', import.meta.url));
  const foundation = JSON.parse(readFileSync(join(root, 'design/foundation.json'), 'utf8'));
  const themesDir = join(root, 'design/themes');
  const themes = readdirSync(themesDir)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((f) => JSON.parse(readFileSync(join(themesDir, f), 'utf8')));

  const violations = contrastViolations(themes);
  if (violations.length > 0) {
    console.error(`Contrast gate FAILED — ${violations.length} pair(s) below ${MIN_RATIO}:1`);
    for (const v of violations) {
      console.error(`  ${v.theme}/${v.mode}  ${v.pair}  ratio ${v.ratio}`);
    }
    process.exit(1);
  }

  const outFile = join(root, 'src/styles/tokens.generated.css');
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, generateCss(foundation, themes));
  console.log(
    `tokens: wrote src/styles/tokens.generated.css ` +
      `(${themes.length} themes, contrast gate ${MIN_RATIO}:1 passed)`,
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
