// Worker bindings (DB, MEDIA, EMAIL, ASSETS) and vars (APP_ORIGIN, EMAIL_FROM,
// …) are generated by `wrangler types` into worker-configuration.d.ts as
// Cloudflare.Env — regenerate with `npm run cf-typegen` after editing
// wrangler.jsonc. Only request-scoped locals live here.
// @fontsource-variable/* packages are CSS-only; declare the side-effect imports
// so `astro check` doesn't flag them (Vite resolves them to the font stylesheet).
declare module '@fontsource-variable/*';

declare namespace App {
  interface Locals {
    user: import('./lib/types').SessionUser | null;
    locale: import('./lib/locales').Locale;
    theme: string;
  }
}
