// Worker bindings (DB, MEDIA, EMAIL, ASSETS) and vars (APP_ORIGIN, EMAIL_FROM,
// …) are generated by `wrangler types` into worker-configuration.d.ts as
// Cloudflare.Env — regenerate with `npm run cf-typegen` after editing
// wrangler.jsonc. Only request-scoped locals live here.
// @fontsource-variable/* packages are CSS-only; declare the side-effect imports
// so `astro check` doesn't flag them (Vite resolves them to the font stylesheet).
declare module '@fontsource-variable/*';

declare namespace Cloudflare {
  interface Env {
    /** Stable HMAC secret; never rotate in place after source records exist. */
    IDENTITY_SOURCE_KEY_SECRET?: string;
    /** Version label pinned with the stable HMAC secret in the database. */
    IDENTITY_SOURCE_KEY_ID?: string;
    /** Stable recovery veto/outbox key; independent from OTP verification. */
    IDENTITY_RECOVERY_KEY_SECRET?: string;
    /** Version label pinned with the stable recovery key in the database. */
    IDENTITY_RECOVERY_KEY_ID?: string;
    /** Planning Center PAT client id; store as a Worker secret, never in DB/vars. */
    PLANNING_CENTER_CLIENT_ID?: string;
    /** Planning Center PAT secret; store as a Worker secret, never in DB/vars. */
    PLANNING_CENTER_SECRET?: string;
    /** Planning Center webhook HMAC secret; store as a Worker secret. */
    PLANNING_CENTER_WEBHOOK_SECRET?: string;
    /** Identifying app + contact URL/email required by Planning Center API. */
    PLANNING_CENTER_USER_AGENT?: string;
  }
}

declare namespace App {
  interface Locals {
    user: import('./lib/types').SessionUser | null;
    // Authentication evidence is intentionally separate from profile data.
    // Sensitive mutations must use hasRecentStepUp rather than user presence.
    assurance: import('./lib/sessionAssurance').SessionAssurance | null;
    locale: import('./lib/locales').Locale;
    theme: string;
    modules: Set<string>;
    // Per-request database seam, opened by src/middleware.ts via openDb: `db` is
    // the D1 binding on the default backend (zero-copy) or a request-scoped
    // postgres.js AppDb on supabase; `dbBackend` names which one.
    db: import('./lib/appDb').AppDb;
    // Raw shared backend for master-only campus management. Feature routes use
    // the campus-scoped `db` above and must not reach through this seam.
    rawDb: import('./lib/appDb').AppDb;
    dbBackend: 'd1' | 'supabase';
    campusMode: 'all' | 'campus';
    campus: import('./lib/campusDb').CampusRow | null;
  }
}
